
//! Autogenerated weights for `pallet_belize_compliance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_compliance
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/compliance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_compliance` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStats` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStats` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn verify_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `307515`
		// Minimum execution time: 42_816_000 picoseconds.
		Weight::from_parts(46_513_000, 307515)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	fn update_risk_level() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `307515`
		// Minimum execution time: 41_344_000 picoseconds.
		Weight::from_parts(44_336_000, 307515)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::WhitelistedAccounts` (r:0 w:1)
	/// Proof: `Compliance::WhitelistedAccounts` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn whitelist_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `307515`
		// Minimum execution time: 44_468_000 picoseconds.
		Weight::from_parts(47_241_000, 307515)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::RestrictedAccounts` (r:1 w:1)
	/// Proof: `Compliance::RestrictedAccounts` (`max_values`: None, `max_size`: Some(307), added: 2782, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStats` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStats` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn restrict_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `307515`
		// Minimum execution time: 55_090_000 picoseconds.
		Weight::from_parts(58_495_000, 307515)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Compliance::SuspiciousActivities` (r:1 w:1)
	/// Proof: `Compliance::SuspiciousActivities` (`max_values`: None, `max_size`: Some(131550), added: 134025, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStats` (r:1 w:1)
	/// Proof: `Compliance::ComplianceStats` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn flag_suspicious_activity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `307515`
		// Minimum execution time: 54_853_000 picoseconds.
		Weight::from_parts(58_336_000, 307515)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Compliance::SanctionsList` (r:1 w:1)
	/// Proof: `Compliance::SanctionsList` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	fn add_sanctions_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3583`
		// Minimum execution time: 18_732_000 picoseconds.
		Weight::from_parts(20_156_000, 3583)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Compliance::SanctionsList` (r:1 w:1)
	/// Proof: `Compliance::SanctionsList` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	fn remove_sanctions_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3583`
		// Minimum execution time: 20_902_000 picoseconds.
		Weight::from_parts(22_505_000, 3583)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn check_compliance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 248_000 picoseconds.
		Weight::from_parts(335_000, 0)
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStatusOf` (r:1 w:0)
	/// Proof: `Compliance::ComplianceStatusOf` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::AuditRecords` (r:1 w:1)
	/// Proof: `Compliance::AuditRecords` (`max_values`: None, `max_size`: Some(304050), added: 306525, mode: `MaxEncodedLen`)
	fn update_verification_level() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `307515`
		// Minimum execution time: 39_551_000 picoseconds.
		Weight::from_parts(42_785_000, 307515)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
