
//! Autogenerated weights for `pallet_belize_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_identity
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/identity/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_identity` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Identity::GlobalPaused` (r:1 w:0)
	/// Proof: `Identity::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::OperationFee` (r:1 w:0)
	/// Proof: `Identity::OperationFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Identity::NextIdentityId` (r:1 w:1)
	/// Proof: `Identity::NextIdentityId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Identity::Identities` (r:0 w:1)
	/// Proof: `Identity::Identities` (`max_values`: None, `max_size`: Some(422), added: 2897, mode: `MaxEncodedLen`)
	fn register_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3529`
		// Minimum execution time: 31_977_000 picoseconds.
		Weight::from_parts(34_275_000, 3529)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Identity::GlobalPaused` (r:1 w:0)
	/// Proof: `Identity::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityOf` (r:2 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::Identities` (r:1 w:1)
	/// Proof: `Identity::Identities` (`max_values`: None, `max_size`: Some(422), added: 2897, mode: `MaxEncodedLen`)
	fn link_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6068`
		// Minimum execution time: 35_912_000 picoseconds.
		Weight::from_parts(38_038_000, 6068)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:0)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::Identities` (r:1 w:1)
	/// Proof: `Identity::Identities` (`max_values`: None, `max_size`: Some(422), added: 2897, mode: `MaxEncodedLen`)
	fn update_did() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `438`
		//  Estimated: `3887`
		// Minimum execution time: 26_526_000 picoseconds.
		Weight::from_parts(28_333_000, 3887)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IssuerBondAmount` (r:1 w:0)
	/// Proof: `Identity::IssuerBondAmount` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnIssuers` (r:1 w:1)
	/// Proof: `Identity::SsnIssuers` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn add_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `289`
		//  Estimated: `1806`
		// Minimum execution time: 20_928_000 picoseconds.
		Weight::from_parts(22_906_000, 1806)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::SsnIssuers` (r:1 w:1)
	/// Proof: `Identity::SsnIssuers` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn remove_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `1806`
		// Minimum execution time: 16_355_000 picoseconds.
		Weight::from_parts(17_780_000, 1806)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::SsnStandardVersion` (r:0 w:1)
	/// Proof: `Identity::SsnStandardVersion` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_standard_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_973_000 picoseconds.
		Weight::from_parts(9_825_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::OperationFee` (r:0 w:1)
	/// Proof: `Identity::OperationFee` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_operation_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_073_000 picoseconds.
		Weight::from_parts(10_092_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IssuerBondAmount` (r:0 w:1)
	/// Proof: `Identity::IssuerBondAmount` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_issuer_bond_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_968_000 picoseconds.
		Weight::from_parts(9_960_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::RateMaxPerWindowSsn` (r:0 w:1)
	/// Proof: `Identity::RateMaxPerWindowSsn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::RateMaxPerWindowBiometrics` (r:0 w:1)
	/// Proof: `Identity::RateMaxPerWindowBiometrics` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::RateMaxPerWindowPassport` (r:0 w:1)
	/// Proof: `Identity::RateMaxPerWindowPassport` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::RateWindowBlocks` (r:0 w:1)
	/// Proof: `Identity::RateWindowBlocks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_rate_limits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_721_000 picoseconds.
		Weight::from_parts(11_797_000, 0)
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Identity::GlobalPaused` (r:0 w:1)
	/// Proof: `Identity::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_001_000 picoseconds.
		Weight::from_parts(9_834_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IssuerBondAmount` (r:1 w:0)
	/// Proof: `Identity::IssuerBondAmount` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IssuerBonds` (r:1 w:1)
	/// Proof: `Identity::IssuerBonds` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn issuer_deposit_bond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `3593`
		// Minimum execution time: 85_959_000 picoseconds.
		Weight::from_parts(89_546_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::SsnIssuers` (r:1 w:0)
	/// Proof: `Identity::SsnIssuers` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `Identity::FlaggedIssuers` (r:1 w:0)
	/// Proof: `Identity::FlaggedIssuers` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IssuerBonds` (r:1 w:1)
	/// Proof: `Identity::IssuerBonds` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn issuer_withdraw_bond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `479`
		//  Estimated: `3593`
		// Minimum execution time: 88_006_000 picoseconds.
		Weight::from_parts(91_301_000, 3593)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::FlaggedIssuers` (r:0 w:1)
	/// Proof: `Identity::FlaggedIssuers` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn flag_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_503_000 picoseconds.
		Weight::from_parts(13_561_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IssuerBonds` (r:1 w:1)
	/// Proof: `Identity::IssuerBonds` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash_issuer_bond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `560`
		//  Estimated: `6196`
		// Minimum execution time: 83_353_000 picoseconds.
		Weight::from_parts(86_210_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Identity::IssuerBonds` (r:1 w:1)
	/// Proof: `Identity::IssuerBonds` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Identity::FlaggedIssuers` (r:0 w:1)
	/// Proof: `Identity::FlaggedIssuers` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn report_bad_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `560`
		//  Estimated: `6196`
		// Minimum execution time: 90_898_000 picoseconds.
		Weight::from_parts(93_971_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Identity::SsnIssuers` (r:1 w:0)
	/// Proof: `Identity::SsnIssuers` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `Identity::FlaggedIssuers` (r:1 w:0)
	/// Proof: `Identity::FlaggedIssuers` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Identity::GlobalPaused` (r:1 w:0)
	/// Proof: `Identity::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Identity::RateWindowBlocks` (r:1 w:0)
	/// Proof: `Identity::RateWindowBlocks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::RateMaxPerWindowSsn` (r:1 w:0)
	/// Proof: `Identity::RateMaxPerWindowSsn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IssuerRate` (r:1 w:1)
	/// Proof: `Identity::IssuerRate` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityOf` (r:1 w:0)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnHashIndex` (r:1 w:1)
	/// Proof: `Identity::SsnHashIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnStandardVersion` (r:1 w:0)
	/// Proof: `Identity::SsnStandardVersion` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnAttestations` (r:1 w:1)
	/// Proof: `Identity::SsnAttestations` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `Identity::AttributeHistory` (r:1 w:1)
	/// Proof: `Identity::AttributeHistory` (`max_values`: None, `max_size`: Some(551), added: 3026, mode: `MaxEncodedLen`)
	fn issue_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `4016`
		// Minimum execution time: 71_403_000 picoseconds.
		Weight::from_parts(75_070_000, 4016)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:0)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnAttestations` (r:1 w:1)
	/// Proof: `Identity::SsnAttestations` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `Identity::AttributeHistory` (r:1 w:1)
	/// Proof: `Identity::AttributeHistory` (`max_values`: None, `max_size`: Some(551), added: 3026, mode: `MaxEncodedLen`)
	/// Storage: `Identity::SsnHashIndex` (r:0 w:1)
	/// Proof: `Identity::SsnHashIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `664`
		//  Estimated: `4016`
		// Minimum execution time: 44_528_000 picoseconds.
		Weight::from_parts(47_049_000, 4016)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
