
//! Autogenerated weights for `pallet_belize_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/staking/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_staking` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Staking::Validators` (r:2 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorCount` (r:1 w:1)
	/// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	fn join_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `319`
		//  Estimated: `6296`
		// Minimum execution time: 66_151_000 picoseconds.
		Weight::from_parts(69_921_000, 6296)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Staking::Validators` (r:1 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::PendingUnbonds` (r:1 w:1)
	/// Proof: `Staking::PendingUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorCount` (r:1 w:1)
	/// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn leave_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `3643`
		// Minimum execution time: 34_358_000 picoseconds.
		Weight::from_parts(36_607_000, 3643)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Staking::PendingUnbonds` (r:1 w:1)
	/// Proof: `Staking::PendingUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `396`
		//  Estimated: `4764`
		// Minimum execution time: 57_816_000 picoseconds.
		Weight::from_parts(60_719_000, 4764)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Staking::Validators` (r:1 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveFLTask` (r:1 w:0)
	/// Proof: `Staking::ActiveFLTask` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ModelSubmissions` (r:1 w:1)
	/// Proof: `Staking::ModelSubmissions` (`max_values`: None, `max_size`: Some(1175), added: 3650, mode: `MaxEncodedLen`)
	fn submit_model_delta() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `4640`
		// Minimum execution time: 38_318_000 picoseconds.
		Weight::from_parts(40_577_000, 4640)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Staking::ActiveFLTask` (r:0 w:1)
	/// Proof: `Staking::ActiveFLTask` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	fn assign_fl_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `0`
		// Minimum execution time: 16_402_000 picoseconds.
		Weight::from_parts(17_737_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Staking::CurrentEpoch` (r:1 w:1)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:2 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ModelSubmissions` (r:1 w:0)
	/// Proof: `Staking::ModelSubmissions` (`max_values`: None, `max_size`: Some(1175), added: 3650, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochRewards` (r:0 w:1)
	/// Proof: `Staking::EpochRewards` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochDomainContributions` (r:0 w:1)
	/// Proof: `Staking::EpochDomainContributions` (`max_values`: Some(1), `max_size`: Some(85), added: 580, mode: `MaxEncodedLen`)
	fn distribute_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `6296`
		// Minimum execution time: 51_091_000 picoseconds.
		Weight::from_parts(54_092_000, 6296)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::QuantumContributions` (r:1 w:1)
	/// Proof: `Staking::QuantumContributions` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorQuantumStatsMap` (r:1 w:1)
	/// Proof: `Staking::ValidatorQuantumStatsMap` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	fn record_quantum_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `242`
		//  Estimated: `3665`
		// Minimum execution time: 33_898_000 picoseconds.
		Weight::from_parts(36_259_000, 3665)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Staking::CurrentEpoch` (r:1 w:0)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorEpochContributions` (r:1 w:1)
	/// Proof: `Staking::OperatorEpochContributions` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorDomainStatsMap` (r:1 w:1)
	/// Proof: `Staking::OperatorDomainStatsMap` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochDomainContributions` (r:1 w:1)
	/// Proof: `Staking::EpochDomainContributions` (`max_values`: Some(1), `max_size`: Some(85), added: 580, mode: `MaxEncodedLen`)
	fn record_domain_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `3598`
		// Minimum execution time: 31_113_000 picoseconds.
		Weight::from_parts(33_327_000, 3598)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEpoch` (r:1 w:0)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::LastClaimedEpoch` (r:1 w:1)
	/// Proof: `Staking::LastClaimedEpoch` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorDomainStatsMap` (r:1 w:1)
	/// Proof: `Staking::OperatorDomainStatsMap` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorQuantumStatsMap` (r:1 w:0)
	/// Proof: `Staking::ValidatorQuantumStatsMap` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_pouw_with_domain_bonus() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `632`
		//  Estimated: `3643`
		// Minimum execution time: 71_908_000 picoseconds.
		Weight::from_parts(75_466_000, 3643)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::SlashingSpans` (r:1 w:1)
	/// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `BelizeJustice::SlashPendingJusticeReview` (r:1 w:1)
	/// Proof: `BelizeJustice::SlashPendingJusticeReview` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn report_validator_offense() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `3643`
		// Minimum execution time: 68_593_000 picoseconds.
		Weight::from_parts(71_974_000, 3643)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
