
//! Autogenerated weights for `pallet_belize_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-19, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked-awesome`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_staking
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --wasm-execution
// compiled
// --output
// pallets/staking/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_belize_staking`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Staking::Validators` (r:2 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorCount` (r:1 w:1)
	/// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	fn join_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `319`
		//  Estimated: `6296`
		// Minimum execution time: 43_870_000 picoseconds.
		Weight::from_parts(50_536_000, 0)
			.saturating_add(Weight::from_parts(0, 6296))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::Validators` (r:1 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::PendingUnbonds` (r:1 w:1)
	/// Proof: `Staking::PendingUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorCount` (r:1 w:1)
	/// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn leave_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `3643`
		// Minimum execution time: 22_404_000 picoseconds.
		Weight::from_parts(24_333_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::PendingUnbonds` (r:1 w:1)
	/// Proof: `Staking::PendingUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `396`
		//  Estimated: `4764`
		// Minimum execution time: 39_072_000 picoseconds.
		Weight::from_parts(49_254_000, 0)
			.saturating_add(Weight::from_parts(0, 4764))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Validators` (r:1 w:1)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveFLTask` (r:1 w:0)
	/// Proof: `Staking::ActiveFLTask` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ModelSubmissions` (r:1 w:1)
	/// Proof: `Staking::ModelSubmissions` (`max_values`: None, `max_size`: Some(1175), added: 3650, mode: `MaxEncodedLen`)
	fn submit_model_delta() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `4640`
		// Minimum execution time: 25_235_000 picoseconds.
		Weight::from_parts(29_268_000, 0)
			.saturating_add(Weight::from_parts(0, 4640))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Staking::ActiveFLTask` (r:0 w:1)
	/// Proof: `Staking::ActiveFLTask` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	fn assign_fl_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `0`
		// Minimum execution time: 11_589_000 picoseconds.
		Weight::from_parts(14_265_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::CurrentEpoch` (r:1 w:1)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:2 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ModelSubmissions` (r:1 w:0)
	/// Proof: `Staking::ModelSubmissions` (`max_values`: None, `max_size`: Some(1175), added: 3650, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochRewards` (r:0 w:1)
	/// Proof: `Staking::EpochRewards` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochDomainContributions` (r:0 w:1)
	/// Proof: `Staking::EpochDomainContributions` (`max_values`: Some(1), `max_size`: Some(85), added: 580, mode: `MaxEncodedLen`)
	fn distribute_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `6296`
		// Minimum execution time: 33_461_000 picoseconds.
		Weight::from_parts(38_527_000, 0)
			.saturating_add(Weight::from_parts(0, 6296))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::QuantumContributions` (r:1 w:1)
	/// Proof: `Staking::QuantumContributions` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorQuantumStatsMap` (r:1 w:1)
	/// Proof: `Staking::ValidatorQuantumStatsMap` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	fn record_quantum_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `242`
		//  Estimated: `3665`
		// Minimum execution time: 22_198_000 picoseconds.
		Weight::from_parts(24_458_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Staking::CurrentEpoch` (r:1 w:0)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorEpochContributions` (r:1 w:1)
	/// Proof: `Staking::OperatorEpochContributions` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorDomainStatsMap` (r:1 w:1)
	/// Proof: `Staking::OperatorDomainStatsMap` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Staking::EpochDomainContributions` (r:1 w:1)
	/// Proof: `Staking::EpochDomainContributions` (`max_values`: Some(1), `max_size`: Some(85), added: 580, mode: `MaxEncodedLen`)
	fn record_domain_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `3598`
		// Minimum execution time: 20_701_000 picoseconds.
		Weight::from_parts(22_429_000, 0)
			.saturating_add(Weight::from_parts(0, 3598))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEpoch` (r:1 w:0)
	/// Proof: `Staking::CurrentEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::LastClaimedEpoch` (r:1 w:1)
	/// Proof: `Staking::LastClaimedEpoch` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorDomainStatsMap` (r:1 w:1)
	/// Proof: `Staking::OperatorDomainStatsMap` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorQuantumStatsMap` (r:1 w:0)
	/// Proof: `Staking::ValidatorQuantumStatsMap` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_pouw_with_domain_bonus() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `632`
		//  Estimated: `3643`
		// Minimum execution time: 45_971_000 picoseconds.
		Weight::from_parts(53_503_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::SlashingSpans` (r:1 w:1)
	/// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `BelizeJustice::SlashPendingJusticeReview` (r:1 w:1)
	/// Proof: `BelizeJustice::SlashPendingJusticeReview` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn report_validator_offense() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `3643`
		// Minimum execution time: 49_529_000 picoseconds.
		Weight::from_parts(56_627_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
