
//! Autogenerated weights for `pallet_belize_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_oracle
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/oracle/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_oracle`.
pub trait WeightInfo {
        fn add_operator() -> Weight;
        fn remove_operator() -> Weight;
        fn submit_price() -> Weight;
        fn verify_merchant() -> Weight;
        fn add_sanction() -> Weight;
        fn remove_sanction() -> Weight;
        fn verify_identity() -> Weight;
        fn register_land() -> Weight;
        fn register_iot_device() -> Weight;
        fn submit_iot_data() -> Weight;
        fn verify_iot_device() -> Weight;
        fn claim_oracle_rewards() -> Weight;
        fn update_exchange_rate() -> Weight;
        fn resolve_kyc_dispute() -> Weight;
        fn submit_behavior_flag() -> Weight;
        fn clear_behavior_flag() -> Weight;
}

/// Weights for `pallet_belize_oracle` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `Oracle::OracleOperators` (r:1 w:1)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::OperatorCount` (r:1 w:1)
        /// Proof: `Oracle::OperatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        fn add_operator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `109`
                //  Estimated: `3514`
                // Minimum execution time: 19_338_000 picoseconds.
                Weight::from_parts(21_062_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:1)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::OperatorCount` (r:1 w:1)
        /// Proof: `Oracle::OperatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        fn remove_operator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `184`
                //  Estimated: `3514`
                // Minimum execution time: 23_944_000 picoseconds.
                Weight::from_parts(25_655_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:4 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::PriceFeeds` (r:1 w:1)
        /// Proof: `Oracle::PriceFeeds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::PriceSubmissions` (r:2 w:1)
        /// Proof: `Oracle::PriceSubmissions` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
        fn submit_price() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `584`
                //  Estimated: `11086`
                // Minimum execution time: 77_976_000 picoseconds.
                Weight::from_parts(81_643_000, 11086)
                        .saturating_add(T::DbWeight::get().reads(7_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::MerchantCategories` (r:0 w:1)
        /// Proof: `Oracle::MerchantCategories` (`max_values`: None, `max_size`: Some(358), added: 2833, mode: `MaxEncodedLen`)
        fn verify_merchant() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `207`
                //  Estimated: `3514`
                // Minimum execution time: 25_052_000 picoseconds.
                Weight::from_parts(26_894_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::SanctionedEntities` (r:0 w:1)
        /// Proof: `Oracle::SanctionedEntities` (`max_values`: None, `max_size`: Some(317), added: 2792, mode: `MaxEncodedLen`)
        fn add_sanction() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 13_465_000 picoseconds.
                Weight::from_parts(14_585_000, 0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::SanctionedEntities` (r:1 w:1)
        /// Proof: `Oracle::SanctionedEntities` (`max_values`: None, `max_size`: Some(317), added: 2792, mode: `MaxEncodedLen`)
        fn remove_sanction() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `201`
                //  Estimated: `3782`
                // Minimum execution time: 22_127_000 picoseconds.
                Weight::from_parts(23_676_000, 3782)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::OracleDisputeFlag` (r:1 w:0)
        /// Proof: `Oracle::OracleDisputeFlag` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::PendingKycSubmissions` (r:1 w:1)
        /// Proof: `Oracle::PendingKycSubmissions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::KycLeadingVote` (r:1 w:1)
        /// Proof: `Oracle::KycLeadingVote` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
        fn verify_identity() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `207`
                //  Estimated: `3594`
                // Minimum execution time: 36_109_000 picoseconds.
                Weight::from_parts(38_050_000, 3594)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::LandRegistryData` (r:1 w:1)
        /// Proof: `Oracle::LandRegistryData` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
        fn register_land() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `207`
                //  Estimated: `3604`
                // Minimum execution time: 27_153_000 picoseconds.
                Weight::from_parts(28_888_000, 3604)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::IoTDevices` (r:1 w:1)
        /// Proof: `Oracle::IoTDevices` (`max_values`: None, `max_size`: Some(214), added: 2689, mode: `MaxEncodedLen`)
        fn register_iot_device() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `109`
                //  Estimated: `3679`
                // Minimum execution time: 18_551_000 picoseconds.
                Weight::from_parts(19_989_000, 3679)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::IoTDevices` (r:1 w:1)
        /// Proof: `Oracle::IoTDevices` (`max_values`: None, `max_size`: Some(214), added: 2689, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::OracleOperatorStatsMap` (r:1 w:1)
        /// Proof: `Oracle::OracleOperatorStatsMap` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
        fn submit_iot_data() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `336`
                //  Estimated: `3679`
                // Minimum execution time: 30_328_000 picoseconds.
                Weight::from_parts(32_250_000, 3679)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::IoTDevices` (r:1 w:1)
        /// Proof: `Oracle::IoTDevices` (`max_values`: None, `max_size`: Some(214), added: 2689, mode: `MaxEncodedLen`)
        fn verify_iot_device() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `374`
                //  Estimated: `3679`
                // Minimum execution time: 29_666_000 picoseconds.
                Weight::from_parts(31_629_000, 3679)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::OracleOperatorStatsMap` (r:1 w:1)
        /// Proof: `Oracle::OracleOperatorStatsMap` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn claim_oracle_rewards() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `448`
                //  Estimated: `6196`
                // Minimum execution time: 94_790_000 picoseconds.
                Weight::from_parts(98_069_000, 6196)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Oracle::ManualExchangeRates` (r:0 w:1)
        /// Proof: `Oracle::ManualExchangeRates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
        fn update_exchange_rate() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 12_679_000 picoseconds.
                Weight::from_parts(13_821_000, 0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::OracleDisputeFlag` (r:1 w:1)
        /// Proof: `Oracle::OracleDisputeFlag` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::KycLeadingVote` (r:0 w:1)
        /// Proof: `Oracle::KycLeadingVote` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
        fn resolve_kyc_dispute() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `184`
                //  Estimated: `3514`
                // Minimum execution time: 31_005_000 picoseconds.
                Weight::from_parts(33_013_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Oracle::OracleOperators` (r:1 w:0)
        /// Proof: `Oracle::OracleOperators` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::PendingBehaviorFlags` (r:2 w:1)
        /// Proof: `Oracle::PendingBehaviorFlags` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
        fn submit_behavior_flag() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `283`
                //  Estimated: `6134`
                // Minimum execution time: 40_922_000 picoseconds.
                Weight::from_parts(43_245_000, 6134)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Oracle::BehaviorFlags` (r:1 w:1)
        /// Proof: `Oracle::BehaviorFlags` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Oracle::BehaviorFlagCooldown` (r:0 w:1)
        /// Proof: `Oracle::BehaviorFlagCooldown` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        fn clear_behavior_flag() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `184`
                //  Estimated: `3514`
                // Minimum execution time: 30_560_000 picoseconds.
                Weight::from_parts(32_568_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn add_operator() -> Weight {
                // Minimum execution time: 19_338_000 picoseconds.
                Weight::from_parts(21_062_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn remove_operator() -> Weight {
                // Minimum execution time: 23_944_000 picoseconds.
                Weight::from_parts(25_655_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn submit_price() -> Weight {
                // Minimum execution time: 77_976_000 picoseconds.
                Weight::from_parts(81_643_000, 11086)
                        .saturating_add(RocksDbWeight::get().reads(7_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn verify_merchant() -> Weight {
                // Minimum execution time: 25_052_000 picoseconds.
                Weight::from_parts(26_894_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn add_sanction() -> Weight {
                // Minimum execution time: 13_465_000 picoseconds.
                Weight::from_parts(14_585_000, 0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn remove_sanction() -> Weight {
                // Minimum execution time: 22_127_000 picoseconds.
                Weight::from_parts(23_676_000, 3782)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn verify_identity() -> Weight {
                // Minimum execution time: 36_109_000 picoseconds.
                Weight::from_parts(38_050_000, 3594)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn register_land() -> Weight {
                // Minimum execution time: 27_153_000 picoseconds.
                Weight::from_parts(28_888_000, 3604)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn register_iot_device() -> Weight {
                // Minimum execution time: 18_551_000 picoseconds.
                Weight::from_parts(19_989_000, 3679)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn submit_iot_data() -> Weight {
                // Minimum execution time: 30_328_000 picoseconds.
                Weight::from_parts(32_250_000, 3679)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn verify_iot_device() -> Weight {
                // Minimum execution time: 29_666_000 picoseconds.
                Weight::from_parts(31_629_000, 3679)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn claim_oracle_rewards() -> Weight {
                // Minimum execution time: 94_790_000 picoseconds.
                Weight::from_parts(98_069_000, 6196)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn update_exchange_rate() -> Weight {
                // Minimum execution time: 12_679_000 picoseconds.
                Weight::from_parts(13_821_000, 0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn resolve_kyc_dispute() -> Weight {
                // Minimum execution time: 31_005_000 picoseconds.
                Weight::from_parts(33_013_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn submit_behavior_flag() -> Weight {
                // Minimum execution time: 40_922_000 picoseconds.
                Weight::from_parts(43_245_000, 6134)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn clear_behavior_flag() -> Weight {
                // Minimum execution time: 30_560_000 picoseconds.
                Weight::from_parts(32_568_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
}
