
//! Autogenerated weights for `pallet_belize_justice`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_justice
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/justice/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_justice`.
pub trait WeightInfo {
        fn open_dispute() -> Weight;
        fn mediator_ruling() -> Weight;
        fn appeal_ruling() -> Weight;
        fn complete_rehabilitation() -> Weight;
        fn add_mediator() -> Weight;
        fn remove_mediator() -> Weight;
}

/// Weights for `pallet_belize_justice` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `BelizeJustice::DisputeCounter` (r:1 w:1)
        /// Proof: `BelizeJustice::DisputeCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::CoolingOffEnd` (r:0 w:1)
        /// Proof: `BelizeJustice::CoolingOffEnd` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::Disputes` (r:0 w:1)
        /// Proof: `BelizeJustice::Disputes` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::RehabilitationStatus` (r:0 w:1)
        /// Proof: `BelizeJustice::RehabilitationStatus` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        fn open_dispute() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `109`
                //  Estimated: `1489`
                // Minimum execution time: 47_164_000 picoseconds.
                Weight::from_parts(49_842_000, 1489)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `TechnicalCouncil::Members` (r:1 w:0)
        /// Proof: `TechnicalCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
        /// Storage: `BelizeJustice::MediatorList` (r:1 w:0)
        /// Proof: `BelizeJustice::MediatorList` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::Disputes` (r:1 w:1)
        /// Proof: `BelizeJustice::Disputes` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::SlashPendingJusticeReview` (r:1 w:0)
        /// Proof: `BelizeJustice::SlashPendingJusticeReview` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn mediator_ruling() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `620`
                //  Estimated: `3642`
                // Minimum execution time: 67_601_000 picoseconds.
                Weight::from_parts(71_135_000, 3642)
                        .saturating_add(T::DbWeight::get().reads(5_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `BelizeJustice::Disputes` (r:1 w:1)
        /// Proof: `BelizeJustice::Disputes` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::AppealedAt` (r:0 w:1)
        /// Proof: `BelizeJustice::AppealedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
        fn appeal_ruling() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `395`
                //  Estimated: `3642`
                // Minimum execution time: 26_758_000 picoseconds.
                Weight::from_parts(28_896_000, 3642)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `BelizeJustice::RehabilitationStatus` (r:1 w:1)
        /// Proof: `BelizeJustice::RehabilitationStatus` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeJustice::CoolingOffEnd` (r:1 w:1)
        /// Proof: `BelizeJustice::CoolingOffEnd` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        fn complete_rehabilitation() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `258`
                //  Estimated: `3517`
                // Minimum execution time: 31_447_000 picoseconds.
                Weight::from_parts(33_429_000, 3517)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `BelizeJustice::MediatorList` (r:1 w:1)
        /// Proof: `BelizeJustice::MediatorList` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
        fn add_mediator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `109`
                //  Estimated: `2126`
                // Minimum execution time: 13_471_000 picoseconds.
                Weight::from_parts(15_025_000, 2126)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `BelizeJustice::MediatorList` (r:1 w:1)
        /// Proof: `BelizeJustice::MediatorList` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
        fn remove_mediator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `168`
                //  Estimated: `2126`
                // Minimum execution time: 17_808_000 picoseconds.
                Weight::from_parts(19_485_000, 2126)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn open_dispute() -> Weight {
                // Minimum execution time: 47_164_000 picoseconds.
                Weight::from_parts(49_842_000, 1489)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn mediator_ruling() -> Weight {
                // Minimum execution time: 67_601_000 picoseconds.
                Weight::from_parts(71_135_000, 3642)
                        .saturating_add(RocksDbWeight::get().reads(5_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn appeal_ruling() -> Weight {
                // Minimum execution time: 26_758_000 picoseconds.
                Weight::from_parts(28_896_000, 3642)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn complete_rehabilitation() -> Weight {
                // Minimum execution time: 31_447_000 picoseconds.
                Weight::from_parts(33_429_000, 3517)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn add_mediator() -> Weight {
                // Minimum execution time: 13_471_000 picoseconds.
                Weight::from_parts(15_025_000, 2126)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn remove_mediator() -> Weight {
                // Minimum execution time: 17_808_000 picoseconds.
                Weight::from_parts(19_485_000, 2126)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
}
