
//! Autogenerated weights for `pallet_belize_community`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_community
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/community/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_community`.
pub trait WeightInfo {
        fn record_participation() -> Weight;
        fn update_srs() -> Weight;
        fn endorse_peer() -> Weight;
        fn set_srs_privacy() -> Weight;
        fn submit_community_proposal() -> Weight;
        fn vote_community_proposal() -> Weight;
        fn withdraw_vote() -> Weight;
        fn finalize_community_proposal() -> Weight;
        fn ethics_council_vote() -> Weight;
        fn sanction_account() -> Weight;
        fn lift_sanction() -> Weight;
        fn complete_education_module() -> Weight;
        fn contribute_to_green_project() -> Weight;
        fn claim_referral_reward() -> Weight;
        fn attest_participation() -> Weight;
}

/// Weights for `pallet_belize_community` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `Community::ParticipationHistory` (r:1 w:1)
        /// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:1)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducationCount` (r:1 w:0)
        /// Proof: `Community::CompletedEducationCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributionStats` (r:1 w:0)
        /// Proof: `Community::GreenContributionStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        /// Storage: `Community::PeerEndorsements` (r:1 w:0)
        /// Proof: `Community::PeerEndorsements` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        fn record_participation() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `164`
                //  Estimated: `4815`
                // Minimum execution time: 68_422_000 picoseconds.
                Weight::from_parts(71_525_000, 4815)
                        .saturating_add(T::DbWeight::get().reads(6_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Community::LastSrsUpdate` (r:1 w:1)
        /// Proof: `Community::LastSrsUpdate` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::ParticipationHistory` (r:1 w:0)
        /// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducationCount` (r:1 w:0)
        /// Proof: `Community::CompletedEducationCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributionStats` (r:1 w:0)
        /// Proof: `Community::GreenContributionStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        /// Storage: `Community::PeerEndorsements` (r:1 w:0)
        /// Proof: `Community::PeerEndorsements` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:0)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        fn update_srs() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `244`
                //  Estimated: `4815`
                // Minimum execution time: 69_501_000 picoseconds.
                Weight::from_parts(72_844_000, 4815)
                        .saturating_add(T::DbWeight::get().reads(7_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Community::SocialResponsibilityScores` (r:2 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::LastEndorsement` (r:1 w:1)
        /// Proof: `Community::LastEndorsement` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
        /// Storage: `Community::PeerEndorsements` (r:1 w:1)
        /// Proof: `Community::PeerEndorsements` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::ParticipationHistory` (r:1 w:0)
        /// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducationCount` (r:1 w:0)
        /// Proof: `Community::CompletedEducationCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributionStats` (r:1 w:0)
        /// Proof: `Community::GreenContributionStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:0)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        fn endorse_peer() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `275`
                //  Estimated: `6178`
                // Minimum execution time: 79_220_000 picoseconds.
                Weight::from_parts(83_387_000, 6178)
                        .saturating_add(T::DbWeight::get().reads(8_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        fn set_srs_privacy() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `187`
                //  Estimated: `3584`
                // Minimum execution time: 20_668_000 picoseconds.
                Weight::from_parts(22_374_000, 3584)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Community::ProposalCount` (r:1 w:1)
        /// Proof: `Community::ProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        /// Storage: `Community::EthicsFilterConfig` (r:1 w:0)
        /// Proof: `Community::EthicsFilterConfig` (`max_values`: Some(1), `max_size`: Some(337), added: 832, mode: `MaxEncodedLen`)
        /// Storage: `Community::SanctionedAccounts` (r:1 w:0)
        /// Proof: `Community::SanctionedAccounts` (`max_values`: None, `max_size`: Some(183), added: 2658, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:0)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:0)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        /// Storage: `Community::CommunityProposals` (r:0 w:1)
        /// Proof: `Community::CommunityProposals` (`max_values`: None, `max_size`: Some(1294), added: 3769, mode: `MaxEncodedLen`)
        fn submit_community_proposal() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `312`
                //  Estimated: `3648`
                // Minimum execution time: 67_242_000 picoseconds.
                Weight::from_parts(70_779_000, 3648)
                        .saturating_add(T::DbWeight::get().reads(5_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Community::CommunityProposals` (r:1 w:1)
        /// Proof: `Community::CommunityProposals` (`max_values`: None, `max_size`: Some(1294), added: 3769, mode: `MaxEncodedLen`)
        /// Storage: `Community::ProposalVotes` (r:1 w:1)
        /// Proof: `Community::ProposalVotes` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:0)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        fn vote_community_proposal() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1528`
                //  Estimated: `4759`
                // Minimum execution time: 39_845_000 picoseconds.
                Weight::from_parts(42_864_000, 4759)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Community::CommunityProposals` (r:1 w:1)
        /// Proof: `Community::CommunityProposals` (`max_values`: None, `max_size`: Some(1294), added: 3769, mode: `MaxEncodedLen`)
        /// Storage: `Community::ProposalVotes` (r:1 w:1)
        /// Proof: `Community::ProposalVotes` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
        fn withdraw_vote() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1512`
                //  Estimated: `4759`
                // Minimum execution time: 35_428_000 picoseconds.
                Weight::from_parts(37_924_000, 4759)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `Community::CommunityProposals` (r:1 w:1)
        /// Proof: `Community::CommunityProposals` (`max_values`: None, `max_size`: Some(1294), added: 3769, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:3 w:3)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn finalize_community_proposal() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1696`
                //  Estimated: `8799`
                // Minimum execution time: 122_162_000 picoseconds.
                Weight::from_parts(126_631_000, 8799)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `Community::EthicsFilterConfig` (r:1 w:0)
        /// Proof: `Community::EthicsFilterConfig` (`max_values`: Some(1), `max_size`: Some(337), added: 832, mode: `MaxEncodedLen`)
        /// Storage: `Community::CommunityProposals` (r:1 w:1)
        /// Proof: `Community::CommunityProposals` (`max_values`: None, `max_size`: Some(1294), added: 3769, mode: `MaxEncodedLen`)
        /// Storage: `Community::EthicsCouncilVotes` (r:10 w:1)
        /// Proof: `Community::EthicsCouncilVotes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn ethics_council_vote() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1917`
                //  Estimated: `26430`
                // Minimum execution time: 105_483_000 picoseconds.
                Weight::from_parts(110_358_000, 26430)
                        .saturating_add(T::DbWeight::get().reads(13_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Community::SanctionedAccounts` (r:0 w:1)
        /// Proof: `Community::SanctionedAccounts` (`max_values`: None, `max_size`: Some(183), added: 2658, mode: `MaxEncodedLen`)
        fn sanction_account() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 13_457_000 picoseconds.
                Weight::from_parts(14_736_000, 0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Community::SanctionedAccounts` (r:0 w:1)
        /// Proof: `Community::SanctionedAccounts` (`max_values`: None, `max_size`: Some(183), added: 2658, mode: `MaxEncodedLen`)
        fn lift_sanction() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 11_427_000 picoseconds.
                Weight::from_parts(12_510_000, 0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Community::EducationModules` (r:1 w:1)
        /// Proof: `Community::EducationModules` (`max_values`: None, `max_size`: Some(430), added: 2905, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducation` (r:1 w:1)
        /// Proof: `Community::CompletedEducation` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducationCount` (r:1 w:1)
        /// Proof: `Community::CompletedEducationCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::ParticipationHistory` (r:1 w:0)
        /// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributionStats` (r:1 w:0)
        /// Proof: `Community::GreenContributionStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        /// Storage: `Community::PeerEndorsements` (r:1 w:0)
        /// Proof: `Community::PeerEndorsements` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:0)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        fn complete_education_module() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1630`
                //  Estimated: `4815`
                // Minimum execution time: 128_370_000 picoseconds.
                Weight::from_parts(136_149_000, 4815)
                        .saturating_add(T::DbWeight::get().reads(8_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `Community::GreenProjects` (r:1 w:1)
        /// Proof: `Community::GreenProjects` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributions` (r:1 w:1)
        /// Proof: `Community::GreenContributions` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
        /// Storage: `Community::GreenContributionStats` (r:1 w:1)
        /// Proof: `Community::GreenContributionStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:1)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::ParticipationHistory` (r:1 w:0)
        /// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
        /// Storage: `Community::CompletedEducationCount` (r:1 w:0)
        /// Proof: `Community::CompletedEducationCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::PeerEndorsements` (r:1 w:0)
        /// Proof: `Community::PeerEndorsements` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `Community::UserProposals` (r:1 w:0)
        /// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
        fn contribute_to_green_project() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1458`
                //  Estimated: `4815`
                // Minimum execution time: 154_511_000 picoseconds.
                Weight::from_parts(160_649_000, 4815)
                        .saturating_add(T::DbWeight::get().reads(9_u64))
                        .saturating_add(T::DbWeight::get().writes(5_u64))
        }
        /// Storage: `Community::ReferralClaimed` (r:1 w:1)
        /// Proof: `Community::ReferralClaimed` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
        /// Storage: `Community::RefereeHasReferrer` (r:1 w:1)
        /// Proof: `Community::RefereeHasReferrer` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `Community::SocialResponsibilityScores` (r:1 w:0)
        /// Proof: `Community::SocialResponsibilityScores` (`max_values`: None, `max_size`: Some(119), added: 2594, mode: `MaxEncodedLen`)
        /// Storage: `Community::ReferralData` (r:1 w:1)
        /// Proof: `Community::ReferralData` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
        fn claim_referral_reward() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `265`
                //  Estimated: `3584`
                // Minimum execution time: 49_697_000 picoseconds.
                Weight::from_parts(52_471_000, 3584)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `TechnicalCouncil::Members` (r:1 w:0)
        /// Proof: `TechnicalCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
        /// Storage: `Community::PendingAttestations` (r:1 w:1)
        /// Proof: `Community::PendingAttestations` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
        /// Storage: `Community::AttestationCount` (r:1 w:1)
        /// Proof: `Community::AttestationCount` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
        /// Storage: `Community::AttestedActivities` (r:0 w:1)
        /// Proof: `Community::AttestedActivities` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
        fn attest_participation() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `256`
                //  Estimated: `3563`
                // Minimum execution time: 51_039_000 picoseconds.
                Weight::from_parts(54_176_000, 3563)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn record_participation() -> Weight {
                // Minimum execution time: 68_422_000 picoseconds.
                Weight::from_parts(71_525_000, 4815)
                        .saturating_add(RocksDbWeight::get().reads(6_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn update_srs() -> Weight {
                // Minimum execution time: 69_501_000 picoseconds.
                Weight::from_parts(72_844_000, 4815)
                        .saturating_add(RocksDbWeight::get().reads(7_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn endorse_peer() -> Weight {
                // Minimum execution time: 79_220_000 picoseconds.
                Weight::from_parts(83_387_000, 6178)
                        .saturating_add(RocksDbWeight::get().reads(8_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn set_srs_privacy() -> Weight {
                // Minimum execution time: 20_668_000 picoseconds.
                Weight::from_parts(22_374_000, 3584)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn submit_community_proposal() -> Weight {
                // Minimum execution time: 67_242_000 picoseconds.
                Weight::from_parts(70_779_000, 3648)
                        .saturating_add(RocksDbWeight::get().reads(5_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn vote_community_proposal() -> Weight {
                // Minimum execution time: 39_845_000 picoseconds.
                Weight::from_parts(42_864_000, 4759)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn withdraw_vote() -> Weight {
                // Minimum execution time: 35_428_000 picoseconds.
                Weight::from_parts(37_924_000, 4759)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn finalize_community_proposal() -> Weight {
                // Minimum execution time: 122_162_000 picoseconds.
                Weight::from_parts(126_631_000, 8799)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn ethics_council_vote() -> Weight {
                // Minimum execution time: 105_483_000 picoseconds.
                Weight::from_parts(110_358_000, 26430)
                        .saturating_add(RocksDbWeight::get().reads(13_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn sanction_account() -> Weight {
                // Minimum execution time: 13_457_000 picoseconds.
                Weight::from_parts(14_736_000, 0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn lift_sanction() -> Weight {
                // Minimum execution time: 11_427_000 picoseconds.
                Weight::from_parts(12_510_000, 0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn complete_education_module() -> Weight {
                // Minimum execution time: 128_370_000 picoseconds.
                Weight::from_parts(136_149_000, 4815)
                        .saturating_add(RocksDbWeight::get().reads(8_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn contribute_to_green_project() -> Weight {
                // Minimum execution time: 154_511_000 picoseconds.
                Weight::from_parts(160_649_000, 4815)
                        .saturating_add(RocksDbWeight::get().reads(9_u64))
                        .saturating_add(RocksDbWeight::get().writes(5_u64))
        }
        fn claim_referral_reward() -> Weight {
                // Minimum execution time: 49_697_000 picoseconds.
                Weight::from_parts(52_471_000, 3584)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn attest_participation() -> Weight {
                // Minimum execution time: 51_039_000 picoseconds.
                Weight::from_parts(54_176_000, 3563)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
}
