
//! Autogenerated weights for `pallet_belize_consensus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-19, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked-awesome`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_consensus
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --wasm-execution
// compiled
// --output
// pallets/consensus/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_belize_consensus`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Consensus::NextModelId` (r:1 w:1)
	/// Proof: `Consensus::NextModelId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ModelsByAccount` (r:1 w:1)
	/// Proof: `Consensus::ModelsByAccount` (`max_values`: None, `max_size`: Some(450), added: 2925, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::AIModels` (r:0 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	fn register_ai_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3915`
		// Minimum execution time: 18_201_000 picoseconds.
		Weight::from_parts(23_700_000, 0)
			.saturating_add(Weight::from_parts(0, 3915))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:1)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::NextValidatorId` (r:1 w:1)
	/// Proof: `Consensus::NextValidatorId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:0 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	fn join_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `120`
		//  Estimated: `4764`
		// Minimum execution time: 47_658_000 picoseconds.
		Weight::from_parts(51_067_000, 0)
			.saturating_add(Weight::from_parts(0, 4764))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:1)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	fn leave_validator() -> Weight {
		// Transitional measured estimate pending dedicated benchmark implementation.
		Weight::from_parts(35_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5787))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Consensus::AIModels` (r:2 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:0)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn validate_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4927`
		//  Estimated: `16182`
		// Minimum execution time: 35_326_000 picoseconds.
		Weight::from_parts(39_433_000, 0)
			.saturating_add(Weight::from_parts(0, 16182))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:1)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::NextRoundId` (r:1 w:1)
	/// Proof: `Consensus::NextRoundId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:0)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Babe::NextRandomness` (r:1 w:0)
	/// Proof: `Babe::NextRandomness` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Babe::EpochStart` (r:1 w:0)
	/// Proof: `Babe::EpochStart` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:0 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	fn start_consensus_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `6777`
		// Minimum execution time: 23_299_000 picoseconds.
		Weight::from_parts(29_132_000, 0)
			.saturating_add(Weight::from_parts(0, 6777))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:0)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:0)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:1 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::AIModels` (r:1 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	fn submit_ai_work() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7759`
		//  Estimated: `509274`
		// Minimum execution time: 50_958_000 picoseconds.
		Weight::from_parts(63_233_000, 0)
			.saturating_add(Weight::from_parts(0, 509274))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:1)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:1 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalize_consensus_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124`
		//  Estimated: `509274`
		// Minimum execution time: 24_174_000 picoseconds.
		Weight::from_parts(28_292_000, 0)
			.saturating_add(Weight::from_parts(0, 509274))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
