
//! Autogenerated weights for `pallet_belize_consensus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_consensus
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/consensus/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_consensus` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Consensus::NextModelId` (r:1 w:1)
	/// Proof: `Consensus::NextModelId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ModelsByAccount` (r:1 w:1)
	/// Proof: `Consensus::ModelsByAccount` (`max_values`: None, `max_size`: Some(450), added: 2925, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::AIModels` (r:0 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	fn register_ai_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3915`
		// Minimum execution time: 25_500_000 picoseconds.
		Weight::from_parts(27_353_000, 3915)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:1)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::NextValidatorId` (r:1 w:1)
	/// Proof: `Consensus::NextValidatorId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:0 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	fn join_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `120`
		//  Estimated: `4764`
		// Minimum execution time: 68_371_000 picoseconds.
		Weight::from_parts(72_161_000, 4764)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Consensus::AIModels` (r:2 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:0)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn validate_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4927`
		//  Estimated: `16182`
		// Minimum execution time: 46_507_000 picoseconds.
		Weight::from_parts(49_287_000, 16182)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:1)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::NextRoundId` (r:1 w:1)
	/// Proof: `Consensus::NextRoundId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:0)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Babe::NextRandomness` (r:1 w:0)
	/// Proof: `Babe::NextRandomness` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Babe::EpochStart` (r:1 w:0)
	/// Proof: `Babe::EpochStart` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:0 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	fn start_consensus_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `6777`
		// Minimum execution time: 32_816_000 picoseconds.
		Weight::from_parts(34_970_000, 6777)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:0)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:0)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:1 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::AIModels` (r:1 w:1)
	/// Proof: `Consensus::AIModels` (`max_values`: None, `max_size`: Some(5121), added: 7596, mode: `MaxEncodedLen`)
	fn submit_ai_work() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7759`
		//  Estimated: `509274`
		// Minimum execution time: 69_601_000 picoseconds.
		Weight::from_parts(73_791_000, 509274)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:1)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusRounds` (r:1 w:1)
	/// Proof: `Consensus::ConsensusRounds` (`max_values`: None, `max_size`: Some(505809), added: 508284, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn finalize_consensus_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124`
		//  Estimated: `509274`
		// Minimum execution time: 30_624_000 picoseconds.
		Weight::from_parts(32_680_000, 509274)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Consensus::ValidatorByAccount` (r:1 w:1)
	/// Proof: `Consensus::ValidatorByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::ConsensusValidators` (r:1 w:1)
	/// Proof: `Consensus::ConsensusValidators` (`max_values`: None, `max_size`: Some(3312), added: 5787, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::PendingValidatorUnbonds` (r:1 w:1)
	/// Proof: `Consensus::PendingValidatorUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::CurrentConsensusRound` (r:1 w:0)
	/// Proof: `Consensus::CurrentConsensusRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Consensus::GlobalAIMetrics` (r:1 w:1)
	/// Proof: `Consensus::GlobalAIMetrics` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn leave_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2887`
		//  Estimated: `6777`
		// Minimum execution time: 43_854_000 picoseconds.
		Weight::from_parts(46_454_000, 6777)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Consensus::PendingValidatorUnbonds` (r:1 w:1)
	/// Proof: `Consensus::PendingValidatorUnbonds` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(899), added: 3374, mode: `MaxEncodedLen`)
	fn withdraw_validator_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `99`
		//  Estimated: `4764`
		// Minimum execution time: 44_032_000 picoseconds.
		Weight::from_parts(46_204_000, 4764)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}
