
//! Autogenerated weights for `pallet_belize_whistleblower`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_whistleblower
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/whistleblower/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_whistleblower`.
pub trait WeightInfo {
        fn submit_report() -> Weight;
        fn review_report() -> Weight;
        fn claim_reward() -> Weight;
        fn fund_whistleblower_pool() -> Weight;
}

/// Weights for `pallet_belize_whistleblower` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `BelizeWhistleblower::ReportsThisBlock` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::ReportsThisBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        /// Storage: `BelizeWhistleblower::ReportCounter` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::ReportCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        /// Storage: `BelizeWhistleblower::Reports` (r:0 w:1)
        /// Proof: `BelizeWhistleblower::Reports` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
        fn submit_report() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `42`
                //  Estimated: `1489`
                // Minimum execution time: 43_175_000 picoseconds.
                Weight::from_parts(45_535_000, 1489)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `BelizeWhistleblower::Reports` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::Reports` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
        /// Storage: `BelizeWhistleblower::WhistleblowerPool` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::WhistleblowerPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `BelizeWhistleblower::EscrowedReward` (r:0 w:1)
        /// Proof: `BelizeWhistleblower::EscrowedReward` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
        fn review_report() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `427`
                //  Estimated: `3668`
                // Minimum execution time: 55_584_000 picoseconds.
                Weight::from_parts(58_550_000, 3668)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `BelizeWhistleblower::Reports` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::Reports` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
        /// Storage: `BelizeWhistleblower::EscrowedReward` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::EscrowedReward` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
        fn claim_reward() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `413`
                //  Estimated: `3668`
                // Minimum execution time: 53_503_000 picoseconds.
                Weight::from_parts(56_649_000, 3668)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `BelizeWhistleblower::WhistleblowerPool` (r:1 w:1)
        /// Proof: `BelizeWhistleblower::WhistleblowerPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        fn fund_whistleblower_pool() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `42`
                //  Estimated: `1501`
                // Minimum execution time: 37_782_000 picoseconds.
                Weight::from_parts(39_947_000, 1501)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn submit_report() -> Weight {
                // Minimum execution time: 43_175_000 picoseconds.
                Weight::from_parts(45_535_000, 1489)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn review_report() -> Weight {
                // Minimum execution time: 55_584_000 picoseconds.
                Weight::from_parts(58_550_000, 3668)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn claim_reward() -> Weight {
                // Minimum execution time: 53_503_000 picoseconds.
                Weight::from_parts(56_649_000, 3668)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn fund_whistleblower_pool() -> Weight {
                // Minimum execution time: 37_782_000 picoseconds.
                Weight::from_parts(39_947_000, 1501)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
}
