
//! Autogenerated weights for `pallet_belize_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_governance
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/governance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_governance` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Oracle::BehaviorFlags` (r:1 w:0)
	/// Proof: `Oracle::BehaviorFlags` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Governance::AccountLastProposal` (r:1 w:1)
	/// Proof: `Governance::AccountLastProposal` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::NextProposalId` (r:1 w:1)
	/// Proof: `Governance::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:0 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `252`
		//  Estimated: `3517`
		// Minimum execution time: 53_345_000 picoseconds.
		Weight::from_parts(55_761_000, 3517)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Oracle::BehaviorFlags` (r:1 w:0)
	/// Proof: `Oracle::BehaviorFlags` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Votes` (r:1 w:1)
	/// Proof: `Governance::Votes` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CommunityRanks` (r:1 w:0)
	/// Proof: `Governance::CommunityRanks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PoUWContributions` (r:1 w:0)
	/// Proof: `Governance::PoUWContributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegationReceivers` (r:1 w:0)
	/// Proof: `Governance::DelegationReceivers` (`max_values`: None, `max_size`: Some(3250), added: 5725, mode: `MaxEncodedLen`)
	/// Storage: `Governance::EffectiveVotingMultiplier` (r:1 w:0)
	/// Proof: `Governance::EffectiveVotingMultiplier` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Governance::AccountVoteParticipation` (r:1 w:1)
	/// Proof: `Governance::AccountVoteParticipation` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Community::ParticipationHistory` (r:1 w:1)
	/// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `921`
		//  Estimated: `6715`
		// Minimum execution time: 79_733_000 picoseconds.
		Weight::from_parts(83_468_000, 6715)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	fn finalize_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `488`
		//  Estimated: `5899`
		// Minimum execution time: 45_977_000 picoseconds.
		Weight::from_parts(47_927_000, 5899)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::CommunityRanks` (r:1 w:1)
	/// Proof: `Governance::CommunityRanks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CouncilMembers` (r:1 w:0)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn update_community_rank() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `3577`
		// Minimum execution time: 28_877_000 picoseconds.
		Weight::from_parts(30_662_000, 3577)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::PoUWContributions` (r:1 w:1)
	/// Proof: `Governance::PoUWContributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CouncilMembers` (r:1 w:0)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn update_pouw_contribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `3577`
		// Minimum execution time: 28_750_000 picoseconds.
		Weight::from_parts(30_756_000, 3577)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::JaguarMode` (r:1 w:0)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalEnactmentBlock` (r:0 w:1)
	/// Proof: `Governance::ProposalEnactmentBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn council_override() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538`
		//  Estimated: `5899`
		// Minimum execution time: 34_080_000 picoseconds.
		Weight::from_parts(36_334_000, 5899)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::LockedParameters` (r:1 w:0)
	/// Proof: `Governance::LockedParameters` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ChainParameters` (r:1 w:1)
	/// Proof: `Governance::ChainParameters` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn update_chain_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361`
		//  Estimated: `3522`
		// Minimum execution time: 26_589_000 picoseconds.
		Weight::from_parts(28_623_000, 3522)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::CouncilMembers` (r:1 w:1)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::BoardComposition` (r:1 w:0)
	/// Proof: `Governance::BoardComposition` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn expire_council_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `3577`
		// Minimum execution time: 21_188_000 picoseconds.
		Weight::from_parts(22_828_000, 3577)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::DepartmentManagers` (r:0 w:1)
	/// Proof: `Governance::DepartmentManagers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn set_department_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_810_000 picoseconds.
		Weight::from_parts(12_830_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::DepartmentManagers` (r:1 w:0)
	/// Proof: `Governance::DepartmentManagers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::NextProposalId` (r:1 w:1)
	/// Proof: `Governance::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DepartmentProposalCount` (r:1 w:1)
	/// Proof: `Governance::DepartmentProposalCount` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `Community::ParticipationHistory` (r:1 w:1)
	/// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
	/// Storage: `Community::UserProposals` (r:1 w:1)
	/// Proof: `Community::UserProposals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:0 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	fn submit_department_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `4815`
		// Minimum execution time: 73_303_000 picoseconds.
		Weight::from_parts(76_781_000, 4815)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Governance::DepartmentManagers` (r:1 w:0)
	/// Proof: `Governance::DepartmentManagers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CrossDepartmentApprovals` (r:1 w:1)
	/// Proof: `Governance::CrossDepartmentApprovals` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	fn approve_cross_department() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `613`
		//  Estimated: `5899`
		// Minimum execution time: 40_252_000 picoseconds.
		Weight::from_parts(42_793_000, 5899)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::BoardComposition` (r:1 w:1)
	/// Proof: `Governance::BoardComposition` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CouncilMembers` (r:1 w:1)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TermExpiryQueue` (r:1 w:1)
	/// Proof: `Governance::TermExpiryQueue` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	fn add_board_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `476`
		//  Estimated: `4510`
		// Minimum execution time: 35_114_000 picoseconds.
		Weight::from_parts(37_194_000, 4510)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::CouncilMembers` (r:1 w:1)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::BoardComposition` (r:1 w:1)
	/// Proof: `Governance::BoardComposition` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TermExpiryQueue` (r:1 w:1)
	/// Proof: `Governance::TermExpiryQueue` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	fn remove_board_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `583`
		//  Estimated: `4510`
		// Minimum execution time: 39_946_000 picoseconds.
		Weight::from_parts(42_611_000, 4510)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::CurrentElection` (r:1 w:0)
	/// Proof: `Governance::CurrentElection` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegateNominees` (r:1 w:1)
	/// Proof: `Governance::DelegateNominees` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn nominate_for_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `3517`
		// Minimum execution time: 21_048_000 picoseconds.
		Weight::from_parts(22_737_000, 3517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::CurrentElection` (r:1 w:0)
	/// Proof: `Governance::CurrentElection` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegateVoters` (r:1 w:1)
	/// Proof: `Governance::DelegateVoters` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegateNominees` (r:1 w:1)
	/// Proof: `Governance::DelegateNominees` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn vote_for_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `433`
		//  Estimated: `3565`
		// Minimum execution time: 34_883_000 picoseconds.
		Weight::from_parts(37_294_000, 3565)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::CouncilMembers` (r:1 w:0)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExecutedProposals` (r:1 w:1)
	/// Proof: `Governance::ExecutedProposals` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalEnactmentBlock` (r:1 w:0)
	/// Proof: `Governance::ProposalEnactmentBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TreasurySpendTracker` (r:1 w:1)
	/// Proof: `Governance::TreasurySpendTracker` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873`
		//  Estimated: `6196`
		// Minimum execution time: 111_108_000 picoseconds.
		Weight::from_parts(115_466_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAmendments` (r:1 w:1)
	/// Proof: `Governance::ProposalAmendments` (`max_values`: None, `max_size`: Some(1315), added: 3790, mode: `MaxEncodedLen`)
	fn amend_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `5899`
		// Minimum execution time: 32_091_000 picoseconds.
		Weight::from_parts(34_162_000, 5899)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::NextProposalId` (r:1 w:0)
	/// Proof: `Governance::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Votes` (r:50 w:0)
	/// Proof: `Governance::Votes` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `Governance::RewardsClaimed` (r:1 w:1)
	/// Proof: `Governance::RewardsClaimed` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TotalRewardsDistributed` (r:1 w:1)
	/// Proof: `Governance::TotalRewardsDistributed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn claim_participation_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `696`
		//  Estimated: `128640`
		// Minimum execution time: 275_643_000 picoseconds.
		Weight::from_parts(284_320_000, 128640)
			.saturating_add(T::DbWeight::get().reads(55_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:0)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalQueue` (r:1 w:1)
	/// Proof: `Governance::ProposalQueue` (`max_values`: None, `max_size`: Some(218), added: 2693, mode: `MaxEncodedLen`)
	fn set_proposal_priority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `5899`
		// Minimum execution time: 27_520_000 picoseconds.
		Weight::from_parts(29_609_000, 5899)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::JaguarMode` (r:1 w:1)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CounterForEmergencyVetoes` (r:0 w:1)
	/// Proof: `Governance::CounterForEmergencyVetoes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn declare_emergency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `1793`
		// Minimum execution time: 24_032_000 picoseconds.
		Weight::from_parts(25_855_000, 1793)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::JaguarMode` (r:1 w:1)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CounterForEmergencyVetoes` (r:0 w:1)
	/// Proof: `Governance::CounterForEmergencyVetoes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn end_emergency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `313`
		//  Estimated: `1793`
		// Minimum execution time: 23_175_000 picoseconds.
		Weight::from_parts(25_105_000, 1793)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::DistrictElections` (r:1 w:1)
	/// Proof: `Governance::DistrictElections` (`max_values`: None, `max_size`: Some(43), added: 2518, mode: `MaxEncodedLen`)
	fn start_district_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3508`
		// Minimum execution time: 19_154_000 picoseconds.
		Weight::from_parts(20_846_000, 3508)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::DistrictElections` (r:1 w:0)
	/// Proof: `Governance::DistrictElections` (`max_values`: None, `max_size`: Some(43), added: 2518, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ElectionCandidates` (r:2 w:1)
	/// Proof: `Governance::ElectionCandidates` (`max_values`: None, `max_size`: Some(627), added: 3102, mode: `MaxEncodedLen`)
	fn register_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `316`
		//  Estimated: `7194`
		// Minimum execution time: 35_653_000 picoseconds.
		Weight::from_parts(37_647_000, 7194)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::DistrictElections` (r:1 w:1)
	/// Proof: `Governance::DistrictElections` (`max_values`: None, `max_size`: Some(43), added: 2518, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ElectionVotes` (r:1 w:1)
	/// Proof: `Governance::ElectionVotes` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ElectionCandidates` (r:1 w:1)
	/// Proof: `Governance::ElectionCandidates` (`max_values`: None, `max_size`: Some(627), added: 3102, mode: `MaxEncodedLen`)
	fn vote_in_district_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `481`
		//  Estimated: `4092`
		// Minimum execution time: 42_131_000 picoseconds.
		Weight::from_parts(44_617_000, 4092)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::DistrictElections` (r:1 w:1)
	/// Proof: `Governance::DistrictElections` (`max_values`: None, `max_size`: Some(43), added: 2518, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ElectionCandidates` (r:201 w:0)
	/// Proof: `Governance::ElectionCandidates` (`max_values`: None, `max_size`: Some(627), added: 3102, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CouncilMembers` (r:0 w:1)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DistrictRepresentation` (r:0 w:1)
	/// Proof: `Governance::DistrictRepresentation` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	fn finalize_district_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `26281`
		//  Estimated: `624492`
		// Minimum execution time: 1_492_042_000 picoseconds.
		Weight::from_parts(1_526_915_000, 624492)
			.saturating_add(T::DbWeight::get().reads(202_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::VoteDelegations` (r:1 w:1)
	/// Proof: `Governance::VoteDelegations` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegationReceivers` (r:1 w:1)
	/// Proof: `Governance::DelegationReceivers` (`max_values`: None, `max_size`: Some(3250), added: 5725, mode: `MaxEncodedLen`)
	fn delegate_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `6715`
		// Minimum execution time: 26_028_000 picoseconds.
		Weight::from_parts(28_179_000, 6715)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::VoteDelegations` (r:1 w:1)
	/// Proof: `Governance::VoteDelegations` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `Governance::DelegationReceivers` (r:1 w:1)
	/// Proof: `Governance::DelegationReceivers` (`max_values`: None, `max_size`: Some(3250), added: 5725, mode: `MaxEncodedLen`)
	fn revoke_delegation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `499`
		//  Estimated: `6715`
		// Minimum execution time: 32_379_000 picoseconds.
		Weight::from_parts(34_498_000, 6715)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::NextReferendumId` (r:1 w:1)
	/// Proof: `Governance::NextReferendumId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::ComplianceStats` (r:1 w:0)
	/// Proof: `Compliance::ComplianceStats` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Referendums` (r:0 w:1)
	/// Proof: `Governance::Referendums` (`max_values`: None, `max_size`: Some(2700), added: 5175, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ReferendumEligibleVoters` (r:0 w:1)
	/// Proof: `Governance::ReferendumEligibleVoters` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn create_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325`
		//  Estimated: `1501`
		// Minimum execution time: 31_120_000 picoseconds.
		Weight::from_parts(33_317_000, 1501)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::Referendums` (r:1 w:1)
	/// Proof: `Governance::Referendums` (`max_values`: None, `max_size`: Some(2700), added: 5175, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ReferendumVotes` (r:1 w:1)
	/// Proof: `Governance::ReferendumVotes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CommunityRanks` (r:1 w:0)
	/// Proof: `Governance::CommunityRanks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PoUWContributions` (r:1 w:0)
	/// Proof: `Governance::PoUWContributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Community::ParticipationHistory` (r:1 w:1)
	/// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
	fn vote_on_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `771`
		//  Estimated: `6165`
		// Minimum execution time: 54_696_000 picoseconds.
		Weight::from_parts(58_319_000, 6165)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Governance::Referendums` (r:1 w:1)
	/// Proof: `Governance::Referendums` (`max_values`: None, `max_size`: Some(2700), added: 5175, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ReferendumEligibleVoters` (r:1 w:0)
	/// Proof: `Governance::ReferendumEligibleVoters` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `516`
		//  Estimated: `6165`
		// Minimum execution time: 31_967_000 picoseconds.
		Weight::from_parts(33_911_000, 6165)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::DistrictBudgets` (r:1 w:1)
	/// Proof: `Governance::DistrictBudgets` (`max_values`: None, `max_size`: Some(461), added: 2936, mode: `MaxEncodedLen`)
	fn allocate_district_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3926`
		// Minimum execution time: 19_146_000 picoseconds.
		Weight::from_parts(20_694_000, 3926)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::NextTreasuryProposalId` (r:1 w:1)
	/// Proof: `Governance::NextTreasuryProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TreasurySpendProposals` (r:0 w:1)
	/// Proof: `Governance::TreasurySpendProposals` (`max_values`: None, `max_size`: Some(855), added: 3330, mode: `MaxEncodedLen`)
	fn propose_treasury_spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `1489`
		// Minimum execution time: 18_981_000 picoseconds.
		Weight::from_parts(20_767_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::CouncilMembers` (r:1 w:0)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TreasurySpendProposals` (r:1 w:1)
	/// Proof: `Governance::TreasurySpendProposals` (`max_values`: None, `max_size`: Some(855), added: 3330, mode: `MaxEncodedLen`)
	fn approve_treasury_spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `637`
		//  Estimated: `4320`
		// Minimum execution time: 35_294_000 picoseconds.
		Weight::from_parts(37_583_000, 4320)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::TreasurySpendProposals` (r:1 w:1)
	/// Proof: `Governance::TreasurySpendProposals` (`max_values`: None, `max_size`: Some(855), added: 3330, mode: `MaxEncodedLen`)
	/// Storage: `Governance::NationalTreasuryReserve` (r:1 w:1)
	/// Proof: `Governance::NationalTreasuryReserve` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TreasurySpendTracker` (r:1 w:1)
	/// Proof: `Governance::TreasurySpendTracker` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_treasury_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `631`
		//  Estimated: `6196`
		// Minimum execution time: 105_795_000 picoseconds.
		Weight::from_parts(109_947_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Governance::DistrictBudgets` (r:2 w:2)
	/// Proof: `Governance::DistrictBudgets` (`max_values`: None, `max_size`: Some(461), added: 2936, mode: `MaxEncodedLen`)
	fn transfer_district_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `331`
		//  Estimated: `6862`
		// Minimum execution time: 29_147_000 picoseconds.
		Weight::from_parts(31_324_000, 6862)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Governance::JaguarMode` (r:1 w:0)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::TreasurySpendTracker` (r:1 w:1)
	/// Proof: `Governance::TreasurySpendTracker` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExecutedProposals` (r:0 w:1)
	/// Proof: `Governance::ExecutedProposals` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn execute_emergency_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `755`
		//  Estimated: `6196`
		// Minimum execution time: 102_838_000 picoseconds.
		Weight::from_parts(106_770_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Governance::JaguarMode` (r:1 w:0)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Referendums` (r:1 w:1)
	/// Proof: `Governance::Referendums` (`max_values`: None, `max_size`: Some(2700), added: 5175, mode: `MaxEncodedLen`)
	fn fast_track_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `526`
		//  Estimated: `6165`
		// Minimum execution time: 30_887_000 picoseconds.
		Weight::from_parts(33_232_000, 6165)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::JaguarMode` (r:1 w:0)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	fn emergency_override_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `5899`
		// Minimum execution time: 30_852_000 picoseconds.
		Weight::from_parts(33_019_000, 5899)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:0)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Votes` (r:1 w:0)
	/// Proof: `Governance::Votes` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `Governance::VoteCommitments` (r:1 w:1)
	/// Proof: `Governance::VoteCommitments` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn commit_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `5899`
		// Minimum execution time: 33_490_000 picoseconds.
		Weight::from_parts(35_678_000, 5899)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::VoteCommitments` (r:1 w:1)
	/// Proof: `Governance::VoteCommitments` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Votes` (r:1 w:1)
	/// Proof: `Governance::Votes` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Proposals` (r:1 w:1)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CommunityRanks` (r:1 w:0)
	/// Proof: `Governance::CommunityRanks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PoUWContributions` (r:1 w:0)
	/// Proof: `Governance::PoUWContributions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::EffectiveVotingMultiplier` (r:1 w:0)
	/// Proof: `Governance::EffectiveVotingMultiplier` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Community::ParticipationHistory` (r:1 w:1)
	/// Proof: `Community::ParticipationHistory` (`max_values`: None, `max_size`: Some(1350), added: 3825, mode: `MaxEncodedLen`)
	fn reveal_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `971`
		//  Estimated: `5899`
		// Minimum execution time: 76_388_000 picoseconds.
		Weight::from_parts(80_558_000, 5899)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Governance::PendingRuntimeUpgrade` (r:1 w:1)
	/// Proof: `Governance::PendingRuntimeUpgrade` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::RuntimeUpgradeRatifications` (r:0 w:1)
	/// Proof: `Governance::RuntimeUpgradeRatifications` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn apply_pending_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300`
		//  Estimated: `1517`
		// Minimum execution time: 20_603_000 picoseconds.
		Weight::from_parts(22_842_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn generate_exit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3593`
		// Minimum execution time: 19_308_000 picoseconds.
		Weight::from_parts(20_816_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `TechnicalCouncil::Members` (r:1 w:0)
	/// Proof: `TechnicalCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GovernanceCouncil::Members` (r:1 w:0)
	/// Proof: `GovernanceCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Governance::PendingRuntimeUpgrade` (r:1 w:0)
	/// Proof: `Governance::PendingRuntimeUpgrade` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::RuntimeUpgradeRatifications` (r:1 w:1)
	/// Proof: `Governance::RuntimeUpgradeRatifications` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn ratify_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `3515`
		// Minimum execution time: 32_438_000 picoseconds.
		Weight::from_parts(34_824_000, 3515)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::Proposals` (r:1 w:0)
	/// Proof: `Governance::Proposals` (`max_values`: None, `max_size`: Some(2434), added: 4909, mode: `MaxEncodedLen`)
	/// Storage: `TechnicalCouncil::Members` (r:1 w:0)
	/// Proof: `TechnicalCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GovernanceCouncil::Members` (r:1 w:0)
	/// Proof: `GovernanceCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Governance::ConstitutionalRatifications` (r:1 w:1)
	/// Proof: `Governance::ConstitutionalRatifications` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	fn ratify_constitutional_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `610`
		//  Estimated: `5899`
		// Minimum execution time: 42_200_000 picoseconds.
		Weight::from_parts(44_826_000, 5899)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::LockedParameters` (r:1 w:1)
	/// Proof: `Governance::LockedParameters` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn lock_chain_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `273`
		//  Estimated: `3515`
		// Minimum execution time: 21_790_000 picoseconds.
		Weight::from_parts(23_723_000, 3515)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::LockedParameters` (r:1 w:1)
	/// Proof: `Governance::LockedParameters` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn unlock_chain_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `328`
		//  Estimated: `3515`
		// Minimum execution time: 24_478_000 picoseconds.
		Weight::from_parts(26_564_000, 3515)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::CouncilMembers` (r:201 w:0)
	/// Proof: `Governance::CouncilMembers` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Governance::JaguarMode` (r:1 w:1)
	/// Proof: `Governance::JaguarMode` (`max_values`: Some(1), `max_size`: Some(308), added: 803, mode: `MaxEncodedLen`)
	/// Storage: `Governance::EmergencyVetoes` (r:67 w:67)
	/// Proof: `Governance::EmergencyVetoes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CounterForEmergencyVetoes` (r:1 w:1)
	/// Proof: `Governance::CounterForEmergencyVetoes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn veto_emergency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `28377`
		//  Estimated: `520977`
		// Minimum execution time: 1_448_665_000 picoseconds.
		Weight::from_parts(1_502_953_000, 520977)
			.saturating_add(T::DbWeight::get().reads(270_u64))
			.saturating_add(T::DbWeight::get().writes(69_u64))
	}
}
