
//! Autogenerated weights for `pallet_belize_bns`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_bns
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/bns/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_bns`.
pub trait WeightInfo {
        fn register_domain() -> Weight;
        fn set_resolution() -> Weight;
        fn transfer_domain() -> Weight;
        fn list_domain() -> Weight;
        fn buy_domain() -> Weight;
        fn unlist_domain() -> Weight;
        fn activate_hosting() -> Weight;
        fn renew_hosting() -> Weight;
        fn deactivate_hosting() -> Weight;
        fn register_external_domain() -> Weight;
        fn verify_external_domain() -> Weight;
        fn update_hosting_content() -> Weight;
        fn create_subdomain() -> Weight;
        fn rollback_content() -> Weight;
        fn update_ssl_certificate() -> Weight;
}

/// Weights for `pallet_belize_bns` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `Bns::DomainRegistry` (r:1 w:1)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::AccountDomains` (r:1 w:1)
        /// Proof: `Bns::AccountDomains` (`max_values`: None, `max_size`: Some(6650), added: 9125, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalDomains` (r:1 w:1)
        /// Proof: `Bns::TotalDomains` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
        fn register_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `179`
                //  Estimated: `10115`
                // Minimum execution time: 96_516_000 picoseconds.
                Weight::from_parts(100_155_000, 10115)
                        .saturating_add(T::DbWeight::get().reads(5_u64))
                        .saturating_add(T::DbWeight::get().writes(5_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:0)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainResolution` (r:0 w:1)
        /// Proof: `Bns::DomainResolution` (`max_values`: None, `max_size`: Some(3700), added: 6175, mode: `MaxEncodedLen`)
        fn set_resolution() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `272`
                //  Estimated: `3641`
                // Minimum execution time: 23_341_000 picoseconds.
                Weight::from_parts(25_344_000, 3641)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:1)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::AccountDomains` (r:2 w:2)
        /// Proof: `Bns::AccountDomains` (`max_values`: None, `max_size`: Some(6650), added: 9125, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainListings` (r:0 w:1)
        /// Proof: `Bns::DomainListings` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
        fn transfer_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `325`
                //  Estimated: `19240`
                // Minimum execution time: 42_305_000 picoseconds.
                Weight::from_parts(44_885_000, 19240)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:0)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainListings` (r:1 w:1)
        /// Proof: `Bns::DomainListings` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
        fn list_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `325`
                //  Estimated: `3641`
                // Minimum execution time: 28_987_000 picoseconds.
                Weight::from_parts(31_319_000, 3641)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Bns::DomainListings` (r:1 w:1)
        /// Proof: `Bns::DomainListings` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:3 w:3)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainRegistry` (r:1 w:1)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::AccountDomains` (r:2 w:2)
        /// Proof: `Bns::AccountDomains` (`max_values`: None, `max_size`: Some(6650), added: 9125, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalMarketplaceRevenue` (r:1 w:1)
        /// Proof: `Bns::TotalMarketplaceRevenue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        fn buy_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `719`
                //  Estimated: `19240`
                // Minimum execution time: 174_391_000 picoseconds.
                Weight::from_parts(180_540_000, 19240)
                        .saturating_add(T::DbWeight::get().reads(8_u64))
                        .saturating_add(T::DbWeight::get().writes(8_u64))
        }
        /// Storage: `Bns::DomainListings` (r:1 w:1)
        /// Proof: `Bns::DomainListings` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
        fn unlist_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `275`
                //  Estimated: `3620`
                // Minimum execution time: 18_361_000 picoseconds.
                Weight::from_parts(19_984_000, 3620)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:0)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::HostedWebsites` (r:1 w:1)
        /// Proof: `Bns::HostedWebsites` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalHostingRevenue` (r:1 w:1)
        /// Proof: `Bns::TotalHostingRevenue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        fn activate_hosting() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `375`
                //  Estimated: `6196`
                // Minimum execution time: 97_011_000 picoseconds.
                Weight::from_parts(100_924_000, 6196)
                        .saturating_add(T::DbWeight::get().reads(5_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `Bns::HostedWebsites` (r:1 w:1)
        /// Proof: `Bns::HostedWebsites` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalHostingRevenue` (r:1 w:1)
        /// Proof: `Bns::TotalHostingRevenue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        fn renew_hosting() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `420`
                //  Estimated: `6196`
                // Minimum execution time: 93_954_000 picoseconds.
                Weight::from_parts(97_990_000, 6196)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `Bns::HostedWebsites` (r:1 w:1)
        /// Proof: `Bns::HostedWebsites` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        fn deactivate_hosting() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `317`
                //  Estimated: `3649`
                // Minimum execution time: 17_442_000 picoseconds.
                Weight::from_parts(19_093_000, 3649)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:0)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::ExternalDomains` (r:1 w:1)
        /// Proof: `Bns::ExternalDomains` (`max_values`: None, `max_size`: Some(302), added: 2777, mode: `MaxEncodedLen`)
        /// Storage: `System::ParentHash` (r:1 w:0)
        /// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
        /// Storage: `System::ExtrinsicCount` (r:1 w:0)
        /// Proof: `System::ExtrinsicCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalHostingRevenue` (r:1 w:1)
        /// Proof: `Bns::TotalHostingRevenue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainVerification` (r:0 w:1)
        /// Proof: `Bns::DomainVerification` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        fn register_external_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `375`
                //  Estimated: `6196`
                // Minimum execution time: 108_855_000 picoseconds.
                Weight::from_parts(113_286_000, 6196)
                        .saturating_add(T::DbWeight::get().reads(7_u64))
                        .saturating_add(T::DbWeight::get().writes(5_u64))
        }
        /// Storage: `Bns::ExternalDomains` (r:1 w:0)
        /// Proof: `Bns::ExternalDomains` (`max_values`: None, `max_size`: Some(302), added: 2777, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainVerification` (r:1 w:1)
        /// Proof: `Bns::DomainVerification` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        fn verify_external_domain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `414`
                //  Estimated: `3767`
                // Minimum execution time: 29_425_000 picoseconds.
                Weight::from_parts(31_693_000, 3767)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `Bns::HostedWebsites` (r:1 w:1)
        /// Proof: `Bns::HostedWebsites` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        /// Storage: `Bns::CurrentContentVersion` (r:1 w:1)
        /// Proof: `Bns::CurrentContentVersion` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainResolution` (r:1 w:0)
        /// Proof: `Bns::DomainResolution` (`max_values`: None, `max_size`: Some(3700), added: 6175, mode: `MaxEncodedLen`)
        /// Storage: `Bns::ContentHistory` (r:0 w:1)
        /// Proof: `Bns::ContentHistory` (`max_values`: None, `max_size`: Some(276), added: 2751, mode: `MaxEncodedLen`)
        fn update_hosting_content() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `335`
                //  Estimated: `7165`
                // Minimum execution time: 40_519_000 picoseconds.
                Weight::from_parts(42_859_000, 7165)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:2 w:1)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::AccountDomains` (r:1 w:1)
        /// Proof: `Bns::AccountDomains` (`max_values`: None, `max_size`: Some(6650), added: 9125, mode: `MaxEncodedLen`)
        /// Storage: `Bns::TotalDomains` (r:1 w:1)
        /// Proof: `Bns::TotalDomains` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
        fn create_subdomain() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `343`
                //  Estimated: `10115`
                // Minimum execution time: 44_292_000 picoseconds.
                Weight::from_parts(46_872_000, 10115)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(3_u64))
        }
        /// Storage: `Bns::HostedWebsites` (r:1 w:1)
        /// Proof: `Bns::HostedWebsites` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
        /// Storage: `Bns::ContentHistory` (r:1 w:2)
        /// Proof: `Bns::ContentHistory` (`max_values`: None, `max_size`: Some(276), added: 2751, mode: `MaxEncodedLen`)
        /// Storage: `Bns::CurrentContentVersion` (r:1 w:1)
        /// Proof: `Bns::CurrentContentVersion` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
        /// Storage: `Bns::DomainResolution` (r:1 w:1)
        /// Proof: `Bns::DomainResolution` (`max_values`: None, `max_size`: Some(3700), added: 6175, mode: `MaxEncodedLen`)
        fn rollback_content() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `1289`
                //  Estimated: `7165`
                // Minimum execution time: 67_696_000 picoseconds.
                Weight::from_parts(71_210_000, 7165)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(5_u64))
        }
        /// Storage: `Bns::DomainRegistry` (r:1 w:0)
        /// Proof: `Bns::DomainRegistry` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
        /// Storage: `Bns::SSLCertificates` (r:0 w:1)
        /// Proof: `Bns::SSLCertificates` (`max_values`: None, `max_size`: Some(318), added: 2793, mode: `MaxEncodedLen`)
        fn update_ssl_certificate() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `272`
                //  Estimated: `3641`
                // Minimum execution time: 24_748_000 picoseconds.
                Weight::from_parts(26_766_000, 3641)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn register_domain() -> Weight {
                // Minimum execution time: 96_516_000 picoseconds.
                Weight::from_parts(100_155_000, 10115)
                        .saturating_add(RocksDbWeight::get().reads(5_u64))
                        .saturating_add(RocksDbWeight::get().writes(5_u64))
        }
        fn set_resolution() -> Weight {
                // Minimum execution time: 23_341_000 picoseconds.
                Weight::from_parts(25_344_000, 3641)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn transfer_domain() -> Weight {
                // Minimum execution time: 42_305_000 picoseconds.
                Weight::from_parts(44_885_000, 19240)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn list_domain() -> Weight {
                // Minimum execution time: 28_987_000 picoseconds.
                Weight::from_parts(31_319_000, 3641)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn buy_domain() -> Weight {
                // Minimum execution time: 174_391_000 picoseconds.
                Weight::from_parts(180_540_000, 19240)
                        .saturating_add(RocksDbWeight::get().reads(8_u64))
                        .saturating_add(RocksDbWeight::get().writes(8_u64))
        }
        fn unlist_domain() -> Weight {
                // Minimum execution time: 18_361_000 picoseconds.
                Weight::from_parts(19_984_000, 3620)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn activate_hosting() -> Weight {
                // Minimum execution time: 97_011_000 picoseconds.
                Weight::from_parts(100_924_000, 6196)
                        .saturating_add(RocksDbWeight::get().reads(5_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn renew_hosting() -> Weight {
                // Minimum execution time: 93_954_000 picoseconds.
                Weight::from_parts(97_990_000, 6196)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn deactivate_hosting() -> Weight {
                // Minimum execution time: 17_442_000 picoseconds.
                Weight::from_parts(19_093_000, 3649)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn register_external_domain() -> Weight {
                // Minimum execution time: 108_855_000 picoseconds.
                Weight::from_parts(113_286_000, 6196)
                        .saturating_add(RocksDbWeight::get().reads(7_u64))
                        .saturating_add(RocksDbWeight::get().writes(5_u64))
        }
        fn verify_external_domain() -> Weight {
                // Minimum execution time: 29_425_000 picoseconds.
                Weight::from_parts(31_693_000, 3767)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn update_hosting_content() -> Weight {
                // Minimum execution time: 40_519_000 picoseconds.
                Weight::from_parts(42_859_000, 7165)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn create_subdomain() -> Weight {
                // Minimum execution time: 44_292_000 picoseconds.
                Weight::from_parts(46_872_000, 10115)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(3_u64))
        }
        fn rollback_content() -> Weight {
                // Minimum execution time: 67_696_000 picoseconds.
                Weight::from_parts(71_210_000, 7165)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        .saturating_add(RocksDbWeight::get().writes(5_u64))
        }
        fn update_ssl_certificate() -> Weight {
                // Minimum execution time: 24_748_000 picoseconds.
                Weight::from_parts(26_766_000, 3641)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
}
