
//! Autogenerated weights for `pallet_belize_moderation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_moderation
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template-with-trait.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/moderation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{
        traits::Get,
        weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for `pallet_belize_moderation`.
pub trait WeightInfo {
        fn flag_content() -> Weight;
        fn review_content() -> Weight;
        fn add_moderator() -> Weight;
        fn remove_moderator() -> Weight;
        fn submit_nawal_assessment() -> Weight;
}

/// Weights for `pallet_belize_moderation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        /// Storage: `BelizeModeration::RuledContent` (r:1 w:0)
        /// Proof: `BelizeModeration::RuledContent` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::ContentFlags` (r:1 w:1)
        /// Proof: `BelizeModeration::ContentFlags` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::FlagCounts` (r:1 w:1)
        /// Proof: `BelizeModeration::FlagCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        fn flag_content() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `6`
                //  Estimated: `3562`
                // Minimum execution time: 26_322_000 picoseconds.
                Weight::from_parts(27_910_000, 3562)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `BelizeModeration::ModeratorSet` (r:1 w:0)
        /// Proof: `BelizeModeration::ModeratorSet` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::ModerationQueue` (r:1 w:1)
        /// Proof: `BelizeModeration::ModerationQueue` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::FlagCounts` (r:0 w:1)
        /// Proof: `BelizeModeration::FlagCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::RuledContent` (r:0 w:1)
        /// Proof: `BelizeModeration::RuledContent` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::NawalAssessments` (r:0 w:1)
        /// Proof: `BelizeModeration::NawalAssessments` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        fn review_content() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `135`
                //  Estimated: `3514`
                // Minimum execution time: 36_925_000 picoseconds.
                Weight::from_parts(39_060_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(4_u64))
        }
        /// Storage: `BelizeModeration::ModeratorSet` (r:1 w:1)
        /// Proof: `BelizeModeration::ModeratorSet` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
        fn add_moderator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `6`
                //  Estimated: `3086`
                // Minimum execution time: 12_519_000 picoseconds.
                Weight::from_parts(13_670_000, 3086)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `BelizeModeration::ModeratorSet` (r:1 w:1)
        /// Proof: `BelizeModeration::ModeratorSet` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
        fn remove_moderator() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `64`
                //  Estimated: `3086`
                // Minimum execution time: 16_381_000 picoseconds.
                Weight::from_parts(17_900_000, 3086)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `BelizeModeration::ModerationQueue` (r:1 w:1)
        /// Proof: `BelizeModeration::ModerationQueue` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::RuledContent` (r:1 w:0)
        /// Proof: `BelizeModeration::RuledContent` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        /// Storage: `BelizeModeration::NawalAssessments` (r:0 w:1)
        /// Proof: `BelizeModeration::NawalAssessments` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
        fn submit_nawal_assessment() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `6`
                //  Estimated: `3514`
                // Minimum execution time: 25_072_000 picoseconds.
                Weight::from_parts(26_786_000, 3514)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
}

/// Fallback weights for the mock runtime, which sets `type WeightInfo = ()`.
///
/// The trait lives in this file for this pallet, so the fallback must live here
/// too — leaving it out breaks every `mock.rs` that sets `WeightInfo = ()`.
impl WeightInfo for () {
        fn flag_content() -> Weight {
                // Minimum execution time: 26_322_000 picoseconds.
                Weight::from_parts(27_910_000, 3562)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
        fn review_content() -> Weight {
                // Minimum execution time: 36_925_000 picoseconds.
                Weight::from_parts(39_060_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(4_u64))
        }
        fn add_moderator() -> Weight {
                // Minimum execution time: 12_519_000 picoseconds.
                Weight::from_parts(13_670_000, 3086)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn remove_moderator() -> Weight {
                // Minimum execution time: 16_381_000 picoseconds.
                Weight::from_parts(17_900_000, 3086)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
        }
        fn submit_nawal_assessment() -> Weight {
                // Minimum execution time: 25_072_000 picoseconds.
                Weight::from_parts(26_786_000, 3514)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
        }
}
