
//! Autogenerated weights for `pallet_belize_mesh`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_mesh
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/mesh/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_mesh` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshConfig` (r:1 w:0)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NodesByOwner` (r:1 w:1)
	/// Proof: `Mesh::NodesByOwner` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `73`
		//  Estimated: `3564`
		// Minimum execution time: 54_608_000 picoseconds.
		Weight::from_parts(57_431_000, 3564)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NodesByOwner` (r:1 w:1)
	/// Proof: `Mesh::NodesByOwner` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	fn deregister_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442`
		//  Estimated: `3593`
		// Minimum execution time: 58_231_000 picoseconds.
		Weight::from_parts(61_368_000, 3593)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn update_node_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `236`
		//  Estimated: `3564`
		// Minimum execution time: 21_020_000 picoseconds.
		Weight::from_parts(22_981_000, 3564)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn node_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `236`
		//  Estimated: `3564`
		// Minimum execution time: 21_987_000 picoseconds.
		Weight::from_parts(23_612_000, 3564)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshConfig` (r:1 w:0)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshTxThisBlock` (r:1 w:1)
	/// Proof: `Mesh::MeshTxThisBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::PendingMeshTransactions` (r:1 w:1)
	/// Proof: `Mesh::PendingMeshTransactions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::ProcessedMeshTransactions` (r:1 w:0)
	/// Proof: `Mesh::ProcessedMeshTransactions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	fn submit_mesh_transaction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `3619`
		// Minimum execution time: 43_755_000 picoseconds.
		Weight::from_parts(46_236_000, 3619)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Mesh::MeshConfig` (r:1 w:0)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshNodes` (r:1 w:1)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::RelayProofs` (r:1 w:1)
	/// Proof: `Mesh::RelayProofs` (`max_values`: None, `max_size`: Some(5522), added: 7997, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	fn submit_relay_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `8987`
		// Minimum execution time: 35_279_000 picoseconds.
		Weight::from_parts(37_501_000, 8987)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Mesh::MeshConfig` (r:1 w:0)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NextAlertId` (r:1 w:1)
	/// Proof: `Mesh::NextAlertId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::ActiveAlertCountPerDistrict` (r:1 w:1)
	/// Proof: `Mesh::ActiveAlertCountPerDistrict` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::EmergencyAlerts` (r:0 w:1)
	/// Proof: `Mesh::EmergencyAlerts` (`max_values`: None, `max_size`: Some(218), added: 2693, mode: `MaxEncodedLen`)
	fn issue_emergency_alert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3486`
		// Minimum execution time: 24_216_000 picoseconds.
		Weight::from_parts(25_767_000, 3486)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Mesh::EmergencyAlerts` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAlerts` (`max_values`: None, `max_size`: Some(218), added: 2693, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::ActiveAlertCountPerDistrict` (r:1 w:1)
	/// Proof: `Mesh::ActiveAlertCountPerDistrict` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	fn resolve_emergency_alert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3683`
		// Minimum execution time: 25_590_000 picoseconds.
		Weight::from_parts(27_385_000, 3683)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:0)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::EmergencyAlerts` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAlerts` (`max_values`: None, `max_size`: Some(218), added: 2693, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::ProcessedMeshTransactions` (r:1 w:1)
	/// Proof: `Mesh::ProcessedMeshTransactions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn confirm_emergency_alert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `384`
		//  Estimated: `3683`
		// Minimum execution time: 35_355_000 picoseconds.
		Weight::from_parts(37_680_000, 3683)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Mesh::MeshConfig` (r:1 w:0)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshNodes` (r:1 w:0)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::MeshBlockHeaders` (r:1 w:1)
	/// Proof: `Mesh::MeshBlockHeaders` (`max_values`: None, `max_size`: Some(162), added: 2637, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	fn relay_block_header() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `3627`
		// Minimum execution time: 33_627_000 picoseconds.
		Weight::from_parts(35_855_000, 3627)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Mesh::RelayRewards` (r:1 w:1)
	/// Proof: `Mesh::RelayRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NetworkStats` (r:1 w:1)
	/// Proof: `Mesh::NetworkStats` (`max_values`: Some(1), `max_size`: Some(72), added: 567, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NodesByOwner` (r:1 w:0)
	/// Proof: `Mesh::NodesByOwner` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::RelayProofs` (r:0 w:1)
	/// Proof: `Mesh::RelayProofs` (`max_values`: None, `max_size`: Some(5522), added: 7997, mode: `MaxEncodedLen`)
	fn claim_relay_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `439`
		//  Estimated: `3593`
		// Minimum execution time: 94_949_000 picoseconds.
		Weight::from_parts(98_481_000, 3593)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Mesh::MeshConfig` (r:0 w:1)
	/// Proof: `Mesh::MeshConfig` (`max_values`: Some(1), `max_size`: Some(7), added: 502, mode: `MaxEncodedLen`)
	fn update_mesh_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_335_000 picoseconds.
		Weight::from_parts(10_239_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_relay_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3593`
		// Minimum execution time: 70_021_000 picoseconds.
		Weight::from_parts(72_829_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Mesh::MeshNodes` (r:1 w:0)
	/// Proof: `Mesh::MeshNodes` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::NodesByOwner` (r:1 w:0)
	/// Proof: `Mesh::NodesByOwner` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::RelayProofs` (r:1 w:1)
	/// Proof: `Mesh::RelayProofs` (`max_values`: None, `max_size`: Some(5522), added: 7997, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::RelayRewards` (r:1 w:1)
	/// Proof: `Mesh::RelayRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn confirm_relay_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `446`
		//  Estimated: `8987`
		// Minimum execution time: 39_797_000 picoseconds.
		Weight::from_parts(42_350_000, 8987)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Mesh::EmergencyAuthorities` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAuthorities` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::EmergencyAuthorityCount` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAuthorityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn add_emergency_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3514`
		// Minimum execution time: 19_031_000 picoseconds.
		Weight::from_parts(20_440_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Mesh::EmergencyAuthorities` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAuthorities` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Mesh::EmergencyAuthorityCount` (r:1 w:1)
	/// Proof: `Mesh::EmergencyAuthorityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_emergency_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3514`
		// Minimum execution time: 24_332_000 picoseconds.
		Weight::from_parts(26_046_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}
