use frame_support::{pallet_prelude::ConstU32, BoundedVec};
use sc_service::ChainType;
use sp_consensus_babe::AuthorityId as BabeId;
use sp_consensus_grandpa::AuthorityId as GrandpaId;
use sp_core::{sr25519, Pair, Public};
use sp_runtime::{
    traits::{IdentifyAccount, Verify},
    MultiSignature,
};

use crate::chain_spec_configs::NetworkConfig;
use belizechain_runtime::{opaque::SessionKeys, AccountId, BABE_GENESIS_EPOCH_CONFIG, WASM_BINARY};

/// Specialized `ChainSpec`. This is a specialization of the general Substrate ChainSpec type.
pub type ChainSpec = sc_service::GenericChainSpec;

/// Generate a crypto pair from seed.
pub fn get_from_seed<TPublic: Public>(seed: &str) -> <TPublic::Pair as Pair>::Public {
    TPublic::Pair::from_string(&format!("//{}", seed), None)
        .expect("static values are valid; qed")
        .public()
}

type AccountPublic = <MultiSignature as Verify>::Signer;

/// Generate an account ID from seed.
pub fn get_account_id_from_seed<TPublic: Public>(seed: &str) -> AccountId
where
    AccountPublic: From<<TPublic::Pair as Pair>::Public>,
{
    AccountPublic::from(get_from_seed::<TPublic>(seed)).into_account()
}

/// Derive the account ID that a session key belongs to.
fn dev_derived_account_ids() -> Vec<AccountId> {
    const DEV_SEEDS: [&str; 6] = ["Alice", "Bob", "Charlie", "Dave", "Eve", "Ferdie"];

    let mut accounts = Vec::with_capacity(DEV_SEEDS.len() * 2);
    for seed in DEV_SEEDS {
        accounts.push(get_account_id_from_seed::<sr25519::Public>(seed));
        // GRANDPA session keys are ed25519, so include those derivations too.
        accounts.push(AccountId::from(get_from_seed::<sp_core::ed25519::Public>(
            seed,
        )));
    }
    accounts
}

/// Protocol id for mainnet peer-to-peer traffic.
pub(crate) const MAINNET_PROTOCOL_ID: &str = "bzc";
/// Protocol id for public-testnet peer-to-peer traffic.
pub(crate) const TESTNET_PROTOCOL_ID: &str = "bzc-testnet";

/// Testnet bootstrap council seats: 12 = 2 per Belize district x 6 districts.
///
/// Produced by `scripts/generate-testnet-council-keys.sh`, which also writes the
/// secret phrases to `generated_keys/testnet-council-keys.json` in plaintext.
/// These are therefore **TESTNET ONLY** — `mainnet_genesis_with_councils()`
/// refuses to build while any of them is seated (see
/// `assert_seats_are_production_grade`).
///
/// Seated in `governance.councilMembers` (the pallet's district roster) *and* in
/// the `GovernanceCouncil` collective, which is the origin behind
/// `GovernanceCouncilMajority`. Before this existed, the collective was never
/// populated on any chain, so every "council-majority" path silently degraded to
/// sudo while the documentation claimed a 4-of-7 signature requirement.
pub(crate) const TESTNET_COUNCIL_BOOTSTRAP: [&str; 12] = [
    "5G6qGnGaVQ73fRPPEoVG1nk94g2EfDfnRY8kcT7u4Cib2uoZ", // Belize-1
    "5CLwjDBNujwr34FimwntYbrV8mjfjGf1r19QD7T6pV4HpmuR", // Belize-2
    "5C7zcmp4RcjMtPUAqc6S4ruqUCiLgiHKsqmLJQviqtXXB3RX", // Cayo-1
    "5HBqT8FWkugUGkhSPZRWk21M2mqsspYHxWhAaYTpfpchcTFm", // Cayo-2
    "5GQZhVsr6X8HPRUE4RaTZoKhHEERseAirTqtwadHJaruNy4W", // OrangeWalk-1
    "5Ec4QmKS2p9PHiqadiuT2RPeVCm18B35QxTd48jVZ2fCm3Gk", // OrangeWalk-2
    "5FguYWnKxcrqzerFDrhueRTzeyopJFNM8daStfACroS4dYCh", // Corozal-1
    "5GpjAQ1neUTpPA7abZKSxF7B1QGNLHFhqvn8ppvTFSwGF9ux", // Corozal-2
    "5FbZzMXGoYks4mdYc37hFgNwvKBGqeHTWLbcqmW6sBrPh8wU", // StannCreek-1
    "5EXE5PZdpLmYgyHTWkeNcFgQNKuyNrwSXijnAnyAznHiKxyJ", // StannCreek-2
    "5GpKH81kQhmurWZycfbCBnHbLaPqnXRVPaKTJAjXZ8Djnby5", // Toledo-1
    "5FCpj1Z7qXgrURBVrXjZz8kNY72ZUEr6Y9DB5gWFPPwM1tjJ", // Toledo-2
];

/// Testnet bootstrap seats for the `TechnicalCouncil` collective (runtime index 7).
///
/// Seven seats, grouped by the domains the council actually gates: protocol
/// (consensus/AI, governance, identity), security (compliance, oracle) and
/// operations (infrastructure, mesh).
///
/// **Seven is the smallest size at which all three thresholds stay distinct** —
/// majority needs 4, supermajority 5, three-quarters 6. At 6 seats the last two
/// would collide, collapsing a "greater than two thirds" vote into a
/// three-quarter one. Generated by `scripts/generate-testnet-council-keys.sh
/// --technical`; TESTNET ONLY and rejected by the mainnet gate.
///
/// Seated in the `TechnicalCouncil` collective, which is the origin behind 14
/// bindings across 12 pallets (`ComplianceOrigin`, `AIAuthorityOrigin`,
/// `EmergencyOrigin`, the oracle/payroll/landledger/whistleblower reviewer
/// origins and more). With the collective empty every one of those silently
/// degraded to sudo.
pub(crate) const TESTNET_TECHNICAL_COUNCIL: [&str; 7] = [
    "5FZM24QN2cASLQcB88VTa7HkxpoLXSSkg7MtZZVJ5cQLr7mZ", // Protocol-1
    "5EHDLXKiGBSmf2d283aSPhYKhaPy7vAP2KjsLFAdmtLbkLjW", // Protocol-2
    "5DZvkdToZn6wDCiXEmYD2d6SbZPhsi6YMTp6JiWmoNiiqzLa", // Protocol-3
    "5HZAwPrN5WeHsKZu3ZPn6Tb5W9boa6mqimfx3dg4tN9T2fJd", // Security-1
    "5GZ3eQw4VbE4M5XdRoiURCNjNJBjhU9tEpPSxs5KjFw97xCw", // Security-2
    "5GH7putB9R4usf6juK7cbRHtnprfJpA2S3sdKxduUdD5DBCv", // Operations-1
    "5F1NLJ9NkwPuUZReLK7djMGGB7qQ2Lm7Ho2xm4T1vdJMXSYU", // Operations-2
];

/// Minimum seats for a council whose majority is meaningful.
/// Mirrors `MIN_COUNCIL_MEMBERS` in `pallet-belize-governance`.
pub(crate) const MIN_COUNCIL_SEATS: usize = 7;

/// Minimum seats for the technical house. Seven keeps the majority (>1/2),
/// supermajority (>2/3) and three-quarters (>=3/4) thresholds distinct.
pub(crate) const MIN_TECHNICAL_SEATS: usize = 7;

/// Mainnet council seats.
///
/// **Empty by design.** No real district representatives have been designated
/// yet, so `mainnet_genesis_with_councils()` intentionally FAILS to build until
/// this is populated. Fill it with 12 SS58 addresses — 2 per district across the
/// 6 Belize districts — generated on air-gapped hardware. See
/// `docs/deployment/MAINNET_KEY_GENERATION.md`.
pub(crate) const MAINNET_COUNCIL: [&str; 0] = [];

/// Mainnet technical council seats.
///
/// **Empty by design**, for the same reason as `MAINNET_COUNCIL`. Must be at
/// least 7 real accounts, and must not overlap `MAINNET_COUNCIL`: a runtime
/// upgrade requires a ratification from each house, so one account seated in
/// both could satisfy both halves alone.
pub(crate) const MAINNET_TECHNICAL_COUNCIL: [&str; 0] = [];

/// Parse SS58 addresses into account IDs, naming the offending address on failure.
fn parse_council_accounts(addresses: &[&str]) -> Result<Vec<AccountId>, String> {
    use sp_core::crypto::Ss58Codec;

    addresses
        .iter()
        .map(|address| {
            AccountId::from_ss58check(address)
                .map_err(|e| format!("council address {address} is not valid SS58: {e:?}"))
        })
        .collect()
}

/// Genesis rows `(account, community_rank, pouw_contribution)` for the governance
/// pallet's council roster.
fn council_roster_genesis(council: &[AccountId]) -> Vec<(AccountId, u32, u32)> {
    council
        .iter()
        .cloned()
        .map(|account| (account, 1u32, 0u32))
        .collect()
}

/// Reject a house that would make its council-majority origins a lie.
///
/// An empty or undersized council cannot carry a majority, and an empty
/// collective silently turns every one of its gated calls into a sudo-only
/// call. Dev-derived and testnet-bootstrap keys are rejected because both have
/// their secrets sitting in a repository or a plaintext file.
fn assert_seats_are_production_grade(
    house: &str,
    council: &[AccountId],
    min_seats: usize,
    bootstrap: &[&str],
) -> Result<(), String> {
    if council.len() < min_seats {
        return Err(format!(
            "mainnet {house} has {} seat(s); at least {min_seats} are required.\n\
             Designate real representatives, generate their keys on air-gapped \
             hardware, and add the SS58 addresses to MAINNET_COUNCIL / \
             MAINNET_TECHNICAL_COUNCIL in node/src/chain_spec.rs. See \
             docs/deployment/MAINNET_KEY_GENERATION.md.",
            council.len()
        ));
    }

    let mut seen = std::collections::BTreeSet::new();
    for seat in council {
        if !seen.insert(seat) {
            return Err(format!("mainnet {house} contains duplicate seat {seat}"));
        }
    }

    let dev_accounts = dev_derived_account_ids();
    if let Some(seat) = council.iter().find(|s| dev_accounts.contains(s)) {
        return Err(format!(
            "mainnet {house} seat {seat} is a well-known Substrate dev account; \
             production councils must use operator-generated keys"
        ));
    }

    let bootstrap = parse_council_accounts(bootstrap)?;
    if let Some(seat) = council.iter().find(|s| bootstrap.contains(s)) {
        return Err(format!(
            "mainnet {house} seat {seat} is a testnet bootstrap key whose secret \
             phrase is stored in plaintext. Generate real mainnet keys."
        ));
    }

    Ok(())
}

/// Reject a bicameral council where one person holds seats in both houses.
///
/// `governance::ratify_runtime_upgrade` requires `technical && governance`
/// ratification, and a single call marks whichever houses the caller belongs to.
/// An account seated in both houses would therefore satisfy both halves on its
/// own, collapsing the bicameral check into a single signature.
fn assert_houses_are_disjoint(
    governance: &[AccountId],
    technical: &[AccountId],
) -> Result<(), String> {
    if let Some(seat) = governance.iter().find(|s| technical.contains(s)) {
        return Err(format!(
            "mainnet council seat {seat} sits in BOTH houses; the GovernanceCouncil and \
             TechnicalCouncil must be disjoint. A runtime upgrade needs a ratification \
             from each house, so a shared member could supply both alone"
        ));
    }

    Ok(())
}

/// Client-facing chain properties (`system_properties` RPC).
///
/// `ss58Format` must match `SS58Prefix` in the runtime (1981, the Belize
/// independence year) — clients otherwise default to 42 and render every
/// address in the wrong format.
fn chain_properties() -> sc_service::Properties {
    let mut properties = sc_service::Properties::new();
    properties.insert("tokenSymbol".into(), "DALLA".into());
    properties.insert("tokenDecimals".into(), 12u32.into());
    properties.insert("ss58Format".into(), 1981u16.into());
    properties
}

/// Generate a BABE authority key pair plus the derived account ID.
pub fn authority_keys_from_seed(s: &str) -> (AccountId, BabeId, GrandpaId) {
    (
        get_account_id_from_seed::<sr25519::Public>(s),
        get_from_seed::<BabeId>(s),
        get_from_seed::<GrandpaId>(s),
    )
}

/// Generate authority keys from explicit seeds.
///
/// The validator account and BABE key are derived from the sr25519 account seed,
/// while GRANDPA uses its own ed25519 seed.
pub fn authority_keys_from_explicit_seeds(
    account_seed: &str,
    babe_seed: &str,
    grandpa_seed: &str,
) -> (AccountId, BabeId, GrandpaId) {
    (
        get_account_id_from_seed::<sr25519::Public>(account_seed),
        get_from_seed::<BabeId>(babe_seed),
        get_from_seed::<GrandpaId>(grandpa_seed),
    )
}

pub fn development_config() -> Result<ChainSpec, String> {
    Ok(ChainSpec::builder(
        WASM_BINARY.ok_or_else(|| "Development wasm not available".to_string())?,
        Default::default(),
    )
    .with_name("BelizeChain Development")
    .with_id("belizechain_dev")
    .with_chain_type(ChainType::Development)
    .with_genesis_config_patch(testnet_genesis(
        // Initial PoA authorities
        vec![authority_keys_from_seed("Alice")],
        // Sudo account
        get_account_id_from_seed::<sr25519::Public>("Alice"),
        // Pre-funded accounts
        vec![
            get_account_id_from_seed::<sr25519::Public>("Alice"),
            get_account_id_from_seed::<sr25519::Public>("Bob"),
            get_account_id_from_seed::<sr25519::Public>("Alice//stash"),
            get_account_id_from_seed::<sr25519::Public>("Bob//stash"),
        ],
        true,
    )?)
    .build())
}

pub fn local_testnet_config() -> Result<ChainSpec, String> {
    Ok(ChainSpec::builder(
        WASM_BINARY.ok_or_else(|| "Development wasm not available".to_string())?,
        Default::default(),
    )
    .with_name("BelizeChain Local Testnet")
    .with_id("belizechain_local")
    .with_chain_type(ChainType::Local)
    .with_genesis_config_patch(testnet_genesis(
        // Initial PoA authorities
        vec![
            authority_keys_from_seed("Alice"),
            authority_keys_from_seed("Bob"),
        ],
        // Sudo account
        get_account_id_from_seed::<sr25519::Public>("Alice"),
        // Pre-funded accounts
        vec![
            get_account_id_from_seed::<sr25519::Public>("Alice"),
            get_account_id_from_seed::<sr25519::Public>("Bob"),
            get_account_id_from_seed::<sr25519::Public>("Charlie"),
            get_account_id_from_seed::<sr25519::Public>("Dave"),
            get_account_id_from_seed::<sr25519::Public>("Eve"),
            get_account_id_from_seed::<sr25519::Public>("Ferdie"),
            get_account_id_from_seed::<sr25519::Public>("Alice//stash"),
            get_account_id_from_seed::<sr25519::Public>("Bob//stash"),
            get_account_id_from_seed::<sr25519::Public>("Charlie//stash"),
            get_account_id_from_seed::<sr25519::Public>("Dave//stash"),
            get_account_id_from_seed::<sr25519::Public>("Eve//stash"),
            get_account_id_from_seed::<sr25519::Public>("Ferdie//stash"),
        ],
        true,
    )?)
    .with_boot_nodes(
        crate::validator_config::BootstrapNodes::testnet()
            .into_iter()
            .filter_map(|addr| addr.parse().ok())
            .collect(),
    )
    .build())
}

pub fn belizechain_mainnet_config() -> Result<ChainSpec, String> {
    belizechain_mainnet_config_with_councils(
        &parse_council_accounts(&MAINNET_COUNCIL)?,
        &parse_council_accounts(&MAINNET_TECHNICAL_COUNCIL)?,
    )
}

/// Build a mainnet chain spec with an explicit council.
///
/// Split out from `belizechain_mainnet_config` so the council gate can reject an
/// unpopulated mainnet while the rest of the spec (metadata, validators,
/// balances) stays testable with a supplied council.
fn belizechain_mainnet_config_with_councils(
    council: &[AccountId],
    technical: &[AccountId],
) -> Result<ChainSpec, String> {
    Ok(ChainSpec::builder(
        WASM_BINARY.ok_or_else(|| "Production wasm not available".to_string())?,
        Default::default(),
    )
    .with_name("BelizeChain")
    .with_id("belizechain")
    .with_chain_type(ChainType::Live)
    .with_protocol_id(MAINNET_PROTOCOL_ID)
    .with_properties(chain_properties())
    .with_genesis_config_patch(mainnet_genesis_with_councils(council, technical)?)
    .with_boot_nodes(
        crate::validator_config::BootstrapNodes::mainnet()
            .into_iter()
            .filter_map(|addr| addr.parse().ok())
            .collect(),
    )
    .build())
}

/// Configure initial storage state for BelizeChain.
fn testnet_genesis(
    initial_authorities: Vec<(AccountId, BabeId, GrandpaId)>,
    root_key: AccountId,
    endowed_accounts: Vec<AccountId>,
    _enable_println: bool,
) -> Result<serde_json::Value, String> {
    let endowment: u128 = 1_000_000 * 1_000_000_000_000; // 1M DALLA with 12 decimals
    let _stash: u128 = 100_000 * 1_000_000_000_000; // 100K DALLA for staking (reserved for future use)

    let testnet_council = parse_council_accounts(&TESTNET_COUNCIL_BOOTSTRAP)?;
    let testnet_technical = parse_council_accounts(&TESTNET_TECHNICAL_COUNCIL)?;

    // Council members must be able to pay transaction fees to propose and vote in
    // the collective, so endow them alongside the seeded dev accounts.
    let mut balances: Vec<(AccountId, u128)> = endowed_accounts
        .iter()
        .cloned()
        .map(|account| (account, endowment))
        .collect();
    for member in testnet_council.iter().chain(testnet_technical.iter()) {
        if !balances.iter().any(|(account, _)| account == member) {
            balances.push((member.clone(), endowment));
        }
    }

    Ok(serde_json::json!({
        "balances": {
            "balances": balances,
        },
        "session": {
            "keys": initial_authorities.iter().map(|(account, babe, grandpa)| {
                (
                    account.clone(),
                    account.clone(),
                    SessionKeys {
                        babe: babe.clone(),
                        grandpa: grandpa.clone(),
                    },
                )
            }).collect::<Vec<_>>(),
        },
        "babe": {
            "epochConfig": Some(BABE_GENESIS_EPOCH_CONFIG),
        },
        "grandpa": {},
        // Sudo key set to root_key (Alice in dev, real key in testnet)
        "sudo": {
            "key": Some(root_key.clone()),
        },

        // BelizeChain custom pallet configurations
        // Note: Economy pallet doesn't have genesis config yet

        "identity": {
            "operationFee": Some(10u128 * 1_000_000_000_000u128), // 10 DALLA with 12 decimals
            "ssnStandardVersion": 1u8,
            "passportStandardVersion": 1u8,
            "initialSsnIssuers": vec![ root_key.clone() ], // Alice as SSB for local
            "initialPassportIssuers": vec![ root_key.clone() ], // Alice as Immigration for local
            "initialBiometricIssuers": vec![ root_key.clone() ],
            "paused": false,
            "startIdentityId": 1u64,
            "issuerBondAmount": Some(1_000u128 * 1_000_000_000_000u128), // 1000 DALLA bond requirement
            "rateWindowBlocks": Some(14_400u32), // ~1 day at 6s blocks
            "rateLimitSsn": Some(500u32),
            "rateLimitPassport": Some(200u32),
            "rateLimitBiometrics": Some(100u32),
        },

        "governance": {
            // District council roster: 2 seats per Belize district, 6 districts.
            "councilMembers": council_roster_genesis(&testnet_council),
            "democracyLaunchPeriod": 28800u32, // 2 days in blocks (6 sec per block)
            "democracyVotingPeriod": 43200u32, // 3 days in blocks
            "democracyMinimumDeposit": 1000u128 * 1_000_000_000_000u128, // 1000 DALLA with 12 decimals
        },

        // The collective that actually backs `GovernanceCouncilMajority`. Seating
        // the same people here is what makes "council-majority" mean something:
        // `EnsureProportionMoreThan<_, 1, 2>` needs more than half of the real
        // members, so 12 seats require 7 signatures.
        "governanceCouncil": {
            "members": testnet_council.clone(),
        },

        // The technical house: protocol, security and operational decisions.
        // Separated from the governance house so the bicameral requirement is a
        // real check rather than one group voting twice.
        "technicalCouncil": {
            "members": testnet_technical.clone(),
        },

        // Community pallet - Phase 5: Education Modules & Green Projects seed data
        "community": {
            "educationModules": vec![
                // Module 1: Financial Literacy
                (
                    0u32, // module_id
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Financial Literacy for Belizeans".to_vec()).unwrap(), // title
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Learn budgeting, savings, and investment strategies tailored for Belize's economy".to_vec()).unwrap(), // description
                    50u64 * 1_000_000_000_000u64, // reward_amount (50 DALLA)
                    200u32, // capacity
                    true, // is_active
                ),
                // Module 2: Sustainable Agriculture
                (
                    1u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Sustainable Farming Techniques".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Modern agriculture practices for Belize: organic farming, water conservation, and crop rotation".to_vec()).unwrap(),
                    75u64 * 1_000_000_000_000u64, // 75 DALLA (higher reward for agriculture)
                    150u32,
                    true,
                ),
                // Module 3: Digital Governance
                (
                    2u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Participating in Digital Democracy".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"How to use BelizeChain for voting, proposals, and community governance".to_vec()).unwrap(),
                    50u64 * 1_000_000_000_000u64,
                    300u32, // Higher capacity for civic education
                    true,
                ),
                // Module 4: Technology Skills
                (
                    3u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Blockchain and Web3 Fundamentals".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Understanding blockchain technology, smart contracts, and the digital economy".to_vec()).unwrap(),
                    60u64 * 1_000_000_000_000u64,
                    200u32,
                    true,
                ),
            ],
            "greenProjects": vec![
                // Project 1: Belize Barrier Reef Conservation
                (
                    0u32, // project_id
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Belize Barrier Reef Conservation".to_vec()).unwrap(), // title
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Protect and restore the Belize Barrier Reef - the second largest in the world".to_vec()).unwrap(), // description
                    1_000_000u64 * 1_000_000_000_000u64, // funding_goal (1M DALLA)
                    0u64, // current_funding
                    true, // is_active
                ),
                // Project 2: Rainforest Protection
                (
                    1u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Maya Mountain Rainforest Protection".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Preserve Belize's ancient rainforests and protect biodiversity hotspots".to_vec()).unwrap(),
                    750_000u64 * 1_000_000_000_000u64, // 750K DALLA
                    0u64,
                    true,
                ),
                // Project 3: Renewable Energy
                (
                    2u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Community Solar Power Initiative".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Install solar panels in rural communities to reduce fossil fuel dependency".to_vec()).unwrap(),
                    500_000u64 * 1_000_000_000_000u64, // 500K DALLA
                    0u64,
                    true,
                ),
                // Project 4: Waste Management
                (
                    3u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Zero-Waste Belize Program".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Implement recycling centers and composting programs in Belize City and San Pedro".to_vec()).unwrap(),
                    300_000u64 * 1_000_000_000_000u64, // 300K DALLA
                    0u64,
                    true,
                ),
                // Project 5: Mangrove Restoration
                (
                    4u32,
                    BoundedVec::<u8, ConstU32<128>>::try_from(b"Coastal Mangrove Restoration".to_vec()).unwrap(),
                    BoundedVec::<u8, ConstU32<256>>::try_from(b"Replant mangroves along the coast to prevent erosion and protect marine ecosystems".to_vec()).unwrap(),
                    400_000u64 * 1_000_000_000_000u64, // 400K DALLA
                    0u64,
                    true,
                ),
            ],
        },
    }))
}

/// Production mainnet genesis configuration
///
/// # Security
/// Validator keys and the root (sudo) key MUST be injected from a secure key
/// management system (e.g. `subkey generate`, HSM, or Vault) before building
/// the production chain spec. Every key below is checked against the standard
/// Substrate dev accounts, so a publicly-derivable key fails the build instead of
/// silently shipping a production genesis anyone can control.
///
/// Rollback: this is genesis-only. An already-running chain is unaffected by
/// changes here; seating members on a live chain uses `setMembers` instead.
fn mainnet_genesis_with_councils(
    council: &[AccountId],
    technical: &[AccountId],
) -> Result<serde_json::Value, String> {
    use sp_core::crypto::Ss58Codec;

    // Fail before building anything: an empty or shared house leaves the
    // council-majority origins decorative or reduces two houses to one.
    assert_seats_are_production_grade(
        "GovernanceCouncil",
        council,
        MIN_COUNCIL_SEATS,
        &TESTNET_COUNCIL_BOOTSTRAP,
    )?;
    assert_seats_are_production_grade(
        "TechnicalCouncil",
        technical,
        MIN_TECHNICAL_SEATS,
        &TESTNET_TECHNICAL_COUNCIL,
    )?;
    assert_houses_are_disjoint(council, technical)?;

    // Production validator session keys
    let initial_authorities: Vec<(AccountId, BabeId, GrandpaId)> = vec![
        (
            AccountId::from_ss58check("5EcjZEJhfQxEsrUWEMpSH6D6vbq1eWsLsYbR7DUDM82bFAuJ")
                .map_err(|e| format!("{:?}", e))?,
            BabeId::from_ss58check("5EcjZEJhfQxEsrUWEMpSH6D6vbq1eWsLsYbR7DUDM82bFAuJ")
                .map_err(|e| format!("{:?}", e))?,
            GrandpaId::from_ss58check("5E2qCsxXwbyywDnmyiQ7ST37bWy4eKZC7F3NDcaPZKz4CikY")
                .map_err(|e| format!("{:?}", e))?,
        ),
        (
            AccountId::from_ss58check("5HTZ2TeVvkuPCgHSQUUiDo78mXdD6PZ58asi2YcziGDUWhV2")
                .map_err(|e| format!("{:?}", e))?,
            BabeId::from_ss58check("5HTZ2TeVvkuPCgHSQUUiDo78mXdD6PZ58asi2YcziGDUWhV2")
                .map_err(|e| format!("{:?}", e))?,
            GrandpaId::from_ss58check("5HERG37DJjXa7ouXHVXv5SdPBkhqdzXkQ6sCgbFoh1k1CbKm")
                .map_err(|e| format!("{:?}", e))?,
        ),
        (
            AccountId::from_ss58check("5HN2uP8iB9a2C28qjz5LhGfNGAFR9JjWnAL7pbfAtnd2oUHC")
                .map_err(|e| format!("{:?}", e))?,
            BabeId::from_ss58check("5HN2uP8iB9a2C28qjz5LhGfNGAFR9JjWnAL7pbfAtnd2oUHC")
                .map_err(|e| format!("{:?}", e))?,
            GrandpaId::from_ss58check("5GqGQWkFvv5f4sLh1TMFpzuXJbcxg1MiP8FQsuLtxFP9N8Yy")
                .map_err(|e| format!("{:?}", e))?,
        ),
        (
            AccountId::from_ss58check("5FgydnGuSshDLWhcaZyG5ZjV1BCs8rhRCc9JDozySKB8g8AE")
                .map_err(|e| format!("{:?}", e))?,
            BabeId::from_ss58check("5FgydnGuSshDLWhcaZyG5ZjV1BCs8rhRCc9JDozySKB8g8AE")
                .map_err(|e| format!("{:?}", e))?,
            GrandpaId::from_ss58check("5HMqcChxxfgjCTLJjSEt3diV47Fhk9Jiy5BSiWAk17JMQriK")
                .map_err(|e| format!("{:?}", e))?,
        ),
    ];

    // Sovereign Founder Root / Sudo Controller (Wicked)
    let root_key = AccountId::from_ss58check("5Cg3Ez7Upm8caDfjonnMKPZ14B3H5daWM75DkYj7yEt4XSKt")
        .map_err(|e| format!("{:?}", e))?;
    // Government of Belize Treasury Sovereign Reserve
    let treasury_key =
        AccountId::from_ss58check("5CJX6HRtMn2bvJM1vncjmyUfRbTVQRUWFxwJH6T6SCqoHjf3")
            .map_err(|e| format!("{:?}", e))?;

    // H-1/M-1: fail the build if any production key is publicly derivable.
    let mut production_accounts: Vec<(&str, AccountId)> = vec![
        ("root/sudo", root_key.clone()),
        ("treasury", treasury_key.clone()),
    ];
    for (account, babe, grandpa) in initial_authorities.iter() {
        production_accounts.push(("validator account", account.clone()));
        // Session keys are compared in their account-ID form: `into_inner()` peels
        // the app-crypto wrapper, and sr25519/ed25519 public keys convert to the
        // same 32-byte AccountId a dev session key would collide with.
        production_accounts.push((
            "validator babe session key",
            AccountId::from(babe.clone().into_inner()),
        ));
        production_accounts.push((
            "validator grandpa session key",
            AccountId::from(grandpa.clone().into_inner()),
        ));
    }
    let dev_accounts = dev_derived_account_ids();
    for (label, account) in production_accounts {
        if dev_accounts.contains(&account) {
            return Err(format!(
                "mainnet {label} is a well-known Substrate dev account ({account}); \
                 production genesis must use operator-generated keys"
            ));
        }
    }

    // Initial 100M DALLA Token Distribution (12 decimals)
    let endowed_balances: Vec<(AccountId, u128)> = vec![
        (treasury_key.clone(), 60_000_000u128 * 1_000_000_000_000u128),
        (root_key.clone(), 20_000_000u128 * 1_000_000_000_000u128),
        (
            initial_authorities[0].0.clone(),
            2_500_000u128 * 1_000_000_000_000u128,
        ),
        (
            initial_authorities[1].0.clone(),
            2_500_000u128 * 1_000_000_000_000u128,
        ),
        (
            initial_authorities[2].0.clone(),
            2_500_000u128 * 1_000_000_000_000u128,
        ),
        (
            initial_authorities[3].0.clone(),
            2_500_000u128 * 1_000_000_000_000u128,
        ),
    ];

    Ok(serde_json::json!({
        "balances": {
            "balances": endowed_balances,
        },
        "session": {
            "keys": initial_authorities.iter().map(|(account, babe, grandpa)| {
                (
                    account.clone(),
                    account.clone(),
                    SessionKeys {
                        babe: babe.clone(),
                        grandpa: grandpa.clone(),
                    },
                )
            }).collect::<Vec<_>>(),
        },
        "babe": {
            "epochConfig": Some(BABE_GENESIS_EPOCH_CONFIG),
        },
        "grandpa": {},
        "sudo": {
            "key": Some(root_key.clone()),
        },

        // BelizeChain custom pallet configurations
        // Note: Economy pallet doesn't have genesis config yet

        "identity": {
            "operationFee": Some(50u128 * 1_000_000_000_000u128), // 50 DALLA for mainnet
            "ssnStandardVersion": 1u8,
            "passportStandardVersion": 1u8,
            // Government of Belize authorized identity issuers (Vital Statistics Unit, Immigration Dept, etc.)
            "initialSsnIssuers": vec![ root_key.clone() ],
            "initialPassportIssuers": vec![ root_key.clone() ],
            "initialBiometricIssuers": vec![ root_key.clone() ],
            "paused": false,
            "startIdentityId": 1u64,
            "issuerBondAmount": Some(100_000u128 * 1_000_000_000_000u128), // 100,000 DALLA bond for mainnet
            "rateWindowBlocks": Some(14_400u32), // ~1 day at 6s blocks
            "rateLimitSsn": Some(200u32), // Stricter limits for mainnet
            "rateLimitPassport": Some(100u32),
            "rateLimitBiometrics": Some(50u32),
        },

        "governance": {
            // District council roster: 2 seats per district across 6 districts.
            "councilMembers": council_roster_genesis(council),
            "democracyLaunchPeriod": 100_800u32, // 7 days in blocks
            "democracyVotingPeriod": 201_600u32, // 14 days in blocks
            "democracyMinimumDeposit": 10_000u128 * 1_000_000_000_000u128, // 10,000 DALLA for mainnet
        },

        // The collective that actually backs `GovernanceCouncilMajority`.
        "governanceCouncil": {
            "members": council.to_vec(),
        },

        // The technical house: protocol, security and operational decisions.
        "technicalCouncil": {
            "members": technical.to_vec(),
        },
    }))
}

/// Environment switch that allows Live-typed specs built from the built-in
/// placeholder seeds (`//validator1`, `//treasury`, …).
///
/// Those derivations are public knowledge, so a spec generated from them hands
/// its sudo, session and endowment accounts to anyone who reads this repository.
/// Local devnets and CI smoke runs opt in explicitly; shared chains must supply
/// operator keys instead — see RULE 4 in
/// `docs/operations/TESTNET_ONLY_RULE_2026-09-18.md`.
pub(crate) const ALLOW_DEV_SEEDS_ENV: &str = "BELIZECHAIN_ALLOW_DEV_SEEDS";

fn dev_seeds_allowed() -> bool {
    std::env::var(ALLOW_DEV_SEEDS_ENV).as_deref() == Ok("1")
}

/// Refuse to emit a shared-chain spec whose accounts are dev-derived unless the
/// caller explicitly opted in.
fn check_key_source(network: &str, allow_dev_seeds: bool) -> Result<(), String> {
    if allow_dev_seeds {
        return Ok(());
    }
    Err(format!(
        "refusing to build the `{network}` chain spec: it is seeded from the built-in \
         placeholder seeds, whose accounts are publicly derivable. Set \
         {ALLOW_DEV_SEEDS_ENV}=1 for local experiments and CI smoke tests, or generate \
         the spec and replace the sudo/session/endowment accounts with operator keys \
         before `build-spec ... --raw`."
    ))
}

/// Generate a public-testnet template from NetworkConfig.
///
/// This template is intended for `build-spec` followed by manual review and
/// editing. Real public testnet launches should use an explicit JSON/raw spec
/// file generated from this template rather than a built-in chain alias.
/// Use `build-spec --disable-default-bootnode` when exporting it, otherwise the
/// CLI injects a loopback bootnode into the generated artifact.
///
/// Requires `BELIZECHAIN_ALLOW_DEV_SEEDS=1`: the preset accounts are dev-derived.
#[allow(dead_code)]
pub(crate) fn public_testnet_config() -> Result<ChainSpec, String> {
    build_public_testnet_config(dev_seeds_allowed())
}

/// Deterministic core of [`public_testnet_config`], testable without env vars.
fn build_public_testnet_config(allow_dev_seeds: bool) -> Result<ChainSpec, String> {
    check_key_source("BelizeChain Public Testnet", allow_dev_seeds)?;

    let config = NetworkConfig::public_testnet();

    let authorities: Vec<(AccountId, BabeId, GrandpaId)> = config
        .initial_authorities
        .iter()
        .map(|(account_seed, grandpa_seed)| {
            authority_keys_from_explicit_seeds(account_seed, account_seed, grandpa_seed)
        })
        .collect();

    let endowed_accounts: Vec<AccountId> = config
        .initial_allocation
        .iter()
        .map(|(seed, _)| get_account_id_from_seed::<sr25519::Public>(seed))
        .collect();

    let root_key = get_account_id_from_seed::<sr25519::Public>("treasury");

    Ok(ChainSpec::builder(
        WASM_BINARY.ok_or_else(|| "Testnet wasm not available".to_string())?,
        Default::default(),
    )
    .with_name(&config.name)
    .with_id(&config.id)
    .with_chain_type(ChainType::Live)
    .with_protocol_id(TESTNET_PROTOCOL_ID)
    .with_properties(chain_properties())
    .with_genesis_config_patch(testnet_genesis(
        authorities,
        root_key,
        endowed_accounts,
        true,
    )?)
    .build())
}

/// Generate staging chain spec (pre-mainnet testing)
/// Used for pre-mainnet rehearsal and final integration tests.
///
/// Requires `BELIZECHAIN_ALLOW_DEV_SEEDS=1`: the preset accounts are dev-derived.
#[allow(dead_code)]
pub(crate) fn staging_config() -> Result<ChainSpec, String> {
    build_staging_config(dev_seeds_allowed())
}

/// Deterministic core of [`staging_config`], testable without env vars.
fn build_staging_config(allow_dev_seeds: bool) -> Result<ChainSpec, String> {
    check_key_source("BelizeChain Staging", allow_dev_seeds)?;

    let config = NetworkConfig::staging();

    let authorities: Vec<(AccountId, BabeId, GrandpaId)> = config
        .initial_authorities
        .iter()
        .map(|(account_seed, grandpa_seed)| {
            authority_keys_from_explicit_seeds(account_seed, account_seed, grandpa_seed)
        })
        .collect();

    let endowed_accounts: Vec<AccountId> = config
        .initial_allocation
        .iter()
        .map(|(seed, _)| get_account_id_from_seed::<sr25519::Public>(seed))
        .collect();

    let root_key = get_account_id_from_seed::<sr25519::Public>("treasury");

    Ok(ChainSpec::builder(
        WASM_BINARY.ok_or_else(|| "Staging wasm not available".to_string())?,
        Default::default(),
    )
    .with_name(&config.name)
    .with_id(&config.id)
    .with_chain_type(ChainType::Live)
    .with_genesis_config_patch(testnet_genesis(
        authorities,
        root_key,
        endowed_accounts,
        false, // No debug println in staging
    )?)
    .build())
}

#[cfg(test)]
mod tests {
    use super::*;
    use sp_core::sr25519;

    // ── authority_keys_from_seed ───────────────────────────────────────────

    #[test]
    fn test_authority_keys_from_seed_deterministic() {
        let keys1 = authority_keys_from_seed("Alice");
        let keys2 = authority_keys_from_seed("Alice");
        assert_eq!(
            keys1.0, keys2.0,
            "AccountId must be deterministic for the same seed"
        );
        assert_eq!(
            keys1.1, keys2.1,
            "BabeId must be deterministic for the same seed"
        );
        assert_eq!(
            keys1.2, keys2.2,
            "GrandpaId must be deterministic for the same seed"
        );
    }

    #[test]
    fn test_authority_keys_from_seed_distinct_for_different_seeds() {
        let alice = authority_keys_from_seed("Alice");
        let bob = authority_keys_from_seed("Bob");
        assert_ne!(
            alice.0, bob.0,
            "Different seeds must yield different AccountIds"
        );
        assert_ne!(
            alice.1, bob.1,
            "Different seeds must yield different BabeIds"
        );
        assert_ne!(
            alice.2, bob.2,
            "Different seeds must yield different GrandpaIds"
        );
    }

    // ── get_account_id_from_seed ───────────────────────────────────────────

    #[test]
    fn test_get_account_id_from_seed_deterministic() {
        let id1 = get_account_id_from_seed::<sr25519::Public>("Alice");
        let id2 = get_account_id_from_seed::<sr25519::Public>("Alice");
        assert_eq!(
            id1, id2,
            "Same seed must produce the same AccountId every time"
        );
    }

    #[test]
    fn test_get_account_id_from_seed_distinct_accounts() {
        let alice = get_account_id_from_seed::<sr25519::Public>("Alice");
        let bob = get_account_id_from_seed::<sr25519::Public>("Bob");
        let charlie = get_account_id_from_seed::<sr25519::Public>("Charlie");
        assert_ne!(alice, bob);
        assert_ne!(alice, charlie);
        assert_ne!(bob, charlie);
    }

    #[test]
    fn test_stash_accounts_differ_from_base_accounts() {
        let alice = get_account_id_from_seed::<sr25519::Public>("Alice");
        let alice_stash = get_account_id_from_seed::<sr25519::Public>("Alice//stash");
        assert_ne!(
            alice, alice_stash,
            "stash account must differ from the base account"
        );
    }

    // ── council gates ──────────────────────────────────────────────────────

    /// A synthetic governance house: 12 distinct seats from seeds that are
    /// neither the well-known dev set nor the testnet bootstrap set.
    fn production_grade_council() -> Vec<AccountId> {
        (1..=12)
            .map(|i| get_account_id_from_seed::<sr25519::Public>(&format!("MainnetCouncil{i}")))
            .collect()
    }

    /// A synthetic technical house, disjoint from `production_grade_council`.
    fn production_grade_technical_council() -> Vec<AccountId> {
        (1..=7)
            .map(|i| get_account_id_from_seed::<sr25519::Public>(&format!("MainnetTechnical{i}")))
            .collect()
    }

    #[test]
    fn test_mainnet_genesis_refuses_unpopulated_councils() {
        // Both houses ship empty because no real representatives have been
        // designated. An empty house reduces its council-majority origins to
        // sudo, so it must fail loudly rather than ship.
        assert!(
            MAINNET_COUNCIL.is_empty() && MAINNET_TECHNICAL_COUNCIL.is_empty(),
            "a house is now populated - replace this test with a success assertion"
        );
        let err = mainnet_genesis_with_councils(&[], &[])
            .err()
            .expect("empty councils must be rejected");
        assert!(
            err.contains("at least 7"),
            "error should name the minimum seat count, got: {err}"
        );
    }

    #[test]
    fn test_gate_rejects_undersized_duplicated_dev_and_bootstrap_seats() {
        let gov = production_grade_council();
        let tech = production_grade_technical_council();

        assert!(
            mainnet_genesis_with_councils(&gov[..6], &tech).is_err(),
            "a 6-seat governance house is below the minimum of 7"
        );
        assert!(
            mainnet_genesis_with_councils(&gov, &tech[..6]).is_err(),
            "a 6-seat technical house is below the minimum of 7"
        );

        let mut duplicated = gov.clone();
        duplicated[1] = duplicated[0].clone();
        assert!(
            mainnet_genesis_with_councils(&duplicated, &tech).is_err(),
            "duplicate seats must be rejected"
        );

        let mut with_dev = gov.clone();
        with_dev[0] = get_account_id_from_seed::<sr25519::Public>("Alice");
        assert!(
            mainnet_genesis_with_councils(&with_dev, &tech).is_err(),
            "well-known dev accounts must be rejected"
        );

        for (bootstrap_addresses, is_technical) in [
            (&TESTNET_COUNCIL_BOOTSTRAP[..], false),
            (&TESTNET_TECHNICAL_COUNCIL[..], true),
        ] {
            let bootstrap = parse_council_accounts(bootstrap_addresses).unwrap();
            let mut governance = gov.clone();
            let mut technical = tech.clone();
            if is_technical {
                technical[0] = bootstrap[0].clone();
            } else {
                governance[0] = bootstrap[0].clone();
            }
            assert!(
                mainnet_genesis_with_councils(&governance, &technical).is_err(),
                "testnet bootstrap keys must be rejected in either house"
            );
        }
    }

    #[test]
    fn test_gate_rejects_one_person_in_both_houses() {
        let gov = production_grade_council();
        let mut tech = production_grade_technical_council();
        tech[0] = gov[0].clone();

        let err = mainnet_genesis_with_councils(&gov, &tech)
            .err()
            .expect("shared membership must be rejected");
        assert!(
            err.contains("BOTH houses"),
            "error should name the bicameral violation, got: {err}"
        );
    }

    #[test]
    fn test_mainnet_genesis_seats_both_houses() {
        let gov = production_grade_council();
        let tech = production_grade_technical_council();
        let genesis = mainnet_genesis_with_councils(&gov, &tech)
            .expect("mainnet genesis must succeed with production-grade councils");
        assert!(
            genesis.get("sudo").is_some(),
            "mainnet genesis must contain sudo configuration"
        );
        assert_eq!(
            genesis["session"]["keys"].as_array().map(|a| a.len()),
            Some(4),
            "mainnet genesis must configure 4 validator session keys"
        );
        assert_eq!(
            genesis["governance"]["councilMembers"].as_array().map(|a| a.len()),
            Some(12),
            "mainnet genesis must seat 12 district council members"
        );
        assert_eq!(
            genesis["governanceCouncil"]["members"].as_array().map(|a| a.len()),
            Some(12),
            "mainnet genesis must seat the GovernanceCouncil collective"
        );
        assert_eq!(
            genesis["technicalCouncil"]["members"].as_array().map(|a| a.len()),
            Some(7),
            "mainnet genesis must seat the TechnicalCouncil collective, otherwise its \
             14 gated origins stay sudo-only"
        );
    }

    #[test]
    fn test_testnet_genesis_seats_council_in_roster_and_collective() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .expect("testnet_genesis must succeed");

        assert_eq!(
            genesis["governance"]["councilMembers"].as_array().map(|a| a.len()),
            Some(12),
            "testnet must seat 12 district council members"
        );
        assert_eq!(
            genesis["governanceCouncil"]["members"].as_array().map(|a| a.len()),
            Some(12),
            "testnet must seat the GovernanceCouncil collective, otherwise \
             GovernanceCouncilMajority can never be satisfied and every \
             council-majority call silently degrades to sudo"
        );
        assert_eq!(
            genesis["technicalCouncil"]["members"].as_array().map(|a| a.len()),
            Some(7),
            "testnet must seat the TechnicalCouncil collective, otherwise its 14 \
             gated origins (compliance, AI authority, emergency, oracle, payroll, \
             landledger, whistleblower, moderation, ...) stay sudo-only"
        );
    }

    #[test]
    fn test_houses_are_disjoint_in_testnet_genesis() {
        // A runtime upgrade needs a ratification from each house, and one call
        // marks whichever houses the caller is in. Overlapping membership would
        // let a single account supply both halves.
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .expect("testnet_genesis must succeed");

        let governance = genesis["governanceCouncil"]["members"].as_array().unwrap();
        let technical = genesis["technicalCouncil"]["members"].as_array().unwrap();
        for seat in technical {
            assert!(
                !governance.contains(seat),
                "seat {seat} must not hold membership in both houses"
            );
        }
    }

    #[test]
    fn test_testnet_spec_applies_council_genesis_to_storage() {
        // `pallet_collective`'s genesis asserts that members are unique and that
        // the count does not exceed MaxMembers. A successful build_storage()
        // therefore proves the runtime ACCEPTED the council patch - not merely
        // that the key is present in the JSON.
        use belizechain_runtime::BuildStorage;

        let spec = build_public_testnet_config(true).expect("public testnet config must build");
        spec.build_storage()
            .expect("testnet genesis, including the council, must apply to storage");
    }

    // ── testnet_genesis structure ──────────────────────────────────────────

    #[test]
    fn test_testnet_genesis_succeeds_with_single_authority() {
        let alice_keys = authority_keys_from_seed("Alice");
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let result = testnet_genesis(
            vec![alice_keys],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        );
        assert!(
            result.is_ok(),
            "testnet_genesis must succeed with valid inputs"
        );
    }

    #[test]
    fn test_testnet_genesis_balances_match_endowed_accounts() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let bob_acct = get_account_id_from_seed::<sr25519::Public>("Bob");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct, bob_acct],
            false,
        )
        .unwrap();
        let balances = genesis["balances"]["balances"].as_array().unwrap();
        // The two endowed accounts, plus one entry per council seat in both
        // houses. Council members must hold funds to pay transaction fees when
        // they propose and vote in the collective; a fee-less member cannot
        // exercise its seat.
        assert_eq!(
            balances.len(),
            2 + TESTNET_COUNCIL_BOOTSTRAP.len() + TESTNET_TECHNICAL_COUNCIL.len(),
            "genesis must fund endowed_accounts plus every council seat"
        );
    }

    #[test]
    fn test_testnet_genesis_session_keys_count() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![
                authority_keys_from_seed("Alice"),
                authority_keys_from_seed("Bob"),
            ],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        let keys = genesis["session"]["keys"].as_array().unwrap();
        assert_eq!(
            keys.len(),
            2,
            "session must list exactly 2 validator key sets"
        );
    }

    #[test]
    fn test_testnet_genesis_babe_has_epoch_config_only() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        // BABE should only have epochConfig — authorities are managed by session
        assert!(
            !genesis["babe"]["epochConfig"].is_null(),
            "babe must have epochConfig"
        );
        assert!(
            genesis["babe"].get("authorities").is_none(),
            "babe must NOT have direct authorities when session manages them"
        );
    }

    #[test]
    fn test_testnet_genesis_grandpa_has_no_authorities() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        // GRANDPA authorities are managed by session, not set directly
        assert!(
            genesis["grandpa"].get("authorities").is_none(),
            "grandpa must NOT have direct authorities when session manages them"
        );
    }

    #[test]
    fn test_testnet_genesis_has_sudo_key() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        // Sudo pallet is still included for testnet bootstrapping (CONS-004).
        // It will be removed before mainnet (Phase 0, Step 0.4).
        assert!(
            genesis.get("sudo").is_some(),
            "sudo must be present in testnet genesis for bootstrapping"
        );
    }

    #[test]
    fn test_testnet_genesis_identity_config_present() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        assert!(
            !genesis["identity"].is_null(),
            "identity pallet genesis config must be present"
        );
        assert!(
            !genesis["identity"]["operationFee"].is_null(),
            "identity operationFee must be configured"
        );
        assert!(
            !genesis["identity"]["paused"].is_null(),
            "identity paused flag must be configured"
        );
    }

    #[test]
    fn test_testnet_genesis_governance_council_nonempty() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        let council = genesis["governance"]["councilMembers"].as_array().unwrap();
        assert!(
            !council.is_empty(),
            "governance council must have at least one member in testnet genesis"
        );
    }

    #[test]
    fn test_testnet_genesis_community_education_modules() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        let modules = genesis["community"]["educationModules"].as_array().unwrap();
        assert_eq!(
            modules.len(),
            4,
            "testnet genesis must include exactly 4 education modules"
        );
    }

    #[test]
    fn test_testnet_genesis_community_green_projects() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct.clone(),
            vec![alice_acct],
            false,
        )
        .unwrap();
        let projects = genesis["community"]["greenProjects"].as_array().unwrap();
        assert_eq!(
            projects.len(),
            5,
            "testnet genesis must include exactly 5 green projects"
        );
    }

    #[test]
    fn test_testnet_genesis_endows_council_without_endowed_accounts() {
        let alice_acct = get_account_id_from_seed::<sr25519::Public>("Alice");
        let genesis = testnet_genesis(
            vec![authority_keys_from_seed("Alice")],
            alice_acct,
            vec![], // no endowed accounts
            false,
        )
        .unwrap();
        let balances = genesis["balances"]["balances"].as_array().unwrap();
        // Endowed accounts are passed through verbatim, but council seats are
        // always funded: a seat that cannot pay a transaction fee cannot vote.
        let expected = TESTNET_COUNCIL_BOOTSTRAP.len() + TESTNET_TECHNICAL_COUNCIL.len();
        assert_eq!(
            balances.len(),
            expected,
            "with no endowed accounts, genesis must fund exactly the council seats"
        );
    }

    // ── ChainSpec builder functions ────────────────────────────────────────
    //
    // These functions require WASM_BINARY to be compiled in (built by the
    // runtime's build.rs via substrate-wasm-builder). They will always succeed
    // in a standard `cargo test` run where the full workspace is compiled.

    #[test]
    fn test_development_config_succeeds() {
        development_config()
            .expect("development_config must succeed: WASM_BINARY must be present in test build");
    }

    #[test]
    fn test_local_testnet_config_succeeds() {
        local_testnet_config()
            .expect("local_testnet_config must succeed: WASM_BINARY must be present in test build");
    }

    #[test]
    fn test_belizechain_mainnet_config_is_blocked_until_council_designated() {
        // The public mainnet entry point must refuse to build while
        // MAINNET_COUNCIL is empty. This is the launch gate: a mainnet with no
        // council has council-majority origins that only sudo can satisfy.
        let err = belizechain_mainnet_config()
            .err()
            .expect("mainnet config must not build with an empty council");
        assert!(
            err.contains("GovernanceCouncil"),
            "the failure should name the empty house, got: {err}"
        );
    }

    #[test]
    fn test_mainnet_spec_declares_client_metadata() {
        let spec = belizechain_mainnet_config_with_councils(
            &production_grade_council(),
            &production_grade_technical_council(),
        )
        .expect("mainnet config must build once councils are supplied");
        let properties = spec.properties();
        assert_eq!(
            properties.get("tokenSymbol").and_then(|v| v.as_str()),
            Some("DALLA")
        );
        assert_eq!(
            properties.get("tokenDecimals").and_then(|v| v.as_u64()),
            Some(12)
        );
        assert_eq!(
            properties.get("ss58Format").and_then(|v| v.as_u64()),
            Some(1981),
            "ss58Format must match the runtime SS58Prefix"
        );
        assert_eq!(spec.protocol_id(), Some(MAINNET_PROTOCOL_ID));
    }

    #[test]
    fn test_dev_derived_account_ids_cover_well_known_dev_accounts() {
        use sp_core::crypto::Ss58Codec;

        let dev_accounts = dev_derived_account_ids();
        assert_eq!(dev_accounts.len(), 12, "6 seeds x (sr25519 + ed25519)");

        // `//Alice` (sr25519) and `//Alice` (ed25519, GRANDPA) must both be caught.
        for ss58 in [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu",
        ] {
            let account = AccountId::from_ss58check(ss58).expect("valid dev address");
            assert!(
                dev_accounts.contains(&account),
                "{ss58} must be recognised as a dev-derived account"
            );
        }
    }

    #[test]
    fn test_public_testnet_config_succeeds_with_dev_seed_allowance() {
        build_public_testnet_config(true)
            .expect("public_testnet_config must succeed with the dev-seed allowance");
    }

    #[test]
    fn test_public_testnet_spec_declares_client_metadata() {
        let spec = build_public_testnet_config(true).expect("testnet template must build");
        let properties = spec.properties();
        assert_eq!(
            properties.get("tokenSymbol").and_then(|v| v.as_str()),
            Some("DALLA")
        );
        assert_eq!(
            properties.get("tokenDecimals").and_then(|v| v.as_u64()),
            Some(12)
        );
        assert_eq!(
            properties.get("ss58Format").and_then(|v| v.as_u64()),
            Some(1981)
        );
        assert_eq!(spec.protocol_id(), Some(TESTNET_PROTOCOL_ID));
    }

    #[test]
    fn test_public_testnet_config_refuses_dev_seeds_by_default() {
        let err = match build_public_testnet_config(false) {
            Ok(_) => panic!("dev-seeded testnet spec must not be built by default"),
            Err(err) => err,
        };
        assert!(
            err.contains(ALLOW_DEV_SEEDS_ENV),
            "refusal must name the opt-in env var: {err}"
        );
    }

    #[test]
    fn test_staging_config_succeeds_with_dev_seed_allowance() {
        build_staging_config(true)
            .expect("staging_config must succeed with the dev-seed allowance");
    }

    #[test]
    fn test_staging_config_refuses_dev_seeds_by_default() {
        let err = match build_staging_config(false) {
            Ok(_) => panic!("dev-seeded staging spec must not be built by default"),
            Err(err) => err,
        };
        assert!(
            err.contains(ALLOW_DEV_SEEDS_ENV),
            "refusal must name the opt-in env var: {err}"
        );
    }
}
