
//! Autogenerated weights for `pallet_belize_interoperability`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_interoperability
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/interoperability/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_interoperability` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Interoperability::BridgeCallsThisBlock` (r:1 w:1)
	/// Proof: `Interoperability::BridgeCallsThisBlock` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::ChainConfigurations` (r:1 w:0)
	/// Proof: `Interoperability::ChainConfigurations` (`max_values`: None, `max_size`: Some(371), added: 2846, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::UserBridgeLocks` (r:1 w:1)
	/// Proof: `Interoperability::UserBridgeLocks` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::NextTxId` (r:1 w:1)
	/// Proof: `Interoperability::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::TotalLockedAssets` (r:1 w:1)
	/// Proof: `Interoperability::TotalLockedAssets` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BridgeTransactions` (r:0 w:1)
	/// Proof: `Interoperability::BridgeTransactions` (`max_values`: None, `max_size`: Some(151717), added: 154192, mode: `MaxEncodedLen`)
	fn initiate_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `185`
		//  Estimated: `6196`
		// Minimum execution time: 162_062_000 picoseconds.
		Weight::from_parts(168_891_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Interoperability::BridgeValidators` (r:1 w:0)
	/// Proof: `Interoperability::BridgeValidators` (`max_values`: None, `max_size`: Some(2765), added: 5240, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BridgeTransactions` (r:1 w:1)
	/// Proof: `Interoperability::BridgeTransactions` (`max_values`: None, `max_size`: Some(151717), added: 154192, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::PendingFinalizations` (r:0 w:1)
	/// Proof: `Interoperability::PendingFinalizations` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn provide_signature() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447`
		//  Estimated: `155182`
		// Minimum execution time: 37_186_000 picoseconds.
		Weight::from_parts(39_764_000, 155182)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Interoperability::NextPoolId` (r:1 w:1)
	/// Proof: `Interoperability::NextPoolId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::LiquidityPools` (r:0 w:1)
	/// Proof: `Interoperability::LiquidityPools` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	fn create_liquidity_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41`
		//  Estimated: `1489`
		// Minimum execution time: 43_031_000 picoseconds.
		Weight::from_parts(45_346_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Interoperability::BridgeValidators` (r:1 w:0)
	/// Proof: `Interoperability::BridgeValidators` (`max_values`: None, `max_size`: Some(2765), added: 5240, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BridgeTransactions` (r:1 w:1)
	/// Proof: `Interoperability::BridgeTransactions` (`max_values`: None, `max_size`: Some(151717), added: 154192, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::TotalLockedAssets` (r:1 w:1)
	/// Proof: `Interoperability::TotalLockedAssets` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::UserBridgeLocks` (r:1 w:1)
	/// Proof: `Interoperability::UserBridgeLocks` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn process_unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `859`
		//  Estimated: `155182`
		// Minimum execution time: 116_358_000 picoseconds.
		Weight::from_parts(121_322_000, 155182)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::NextMessageId` (r:1 w:1)
	/// Proof: `Interoperability::NextMessageId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::CrossChainMessages` (r:0 w:1)
	/// Proof: `Interoperability::CrossChainMessages` (`max_values`: None, `max_size`: Some(2117), added: 4592, mode: `MaxEncodedLen`)
	fn send_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `144`
		//  Estimated: `3593`
		// Minimum execution time: 77_639_000 picoseconds.
		Weight::from_parts(81_273_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Interoperability::ChainConfigurations` (r:1 w:1)
	/// Proof: `Interoperability::ChainConfigurations` (`max_values`: None, `max_size`: Some(371), added: 2846, mode: `MaxEncodedLen`)
	fn update_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3836`
		// Minimum execution time: 22_103_000 picoseconds.
		Weight::from_parts(24_010_000, 3836)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Interoperability::BridgeValidators` (r:1 w:0)
	/// Proof: `Interoperability::BridgeValidators` (`max_values`: None, `max_size`: Some(2765), added: 5240, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BridgeTransactions` (r:1 w:1)
	/// Proof: `Interoperability::BridgeTransactions` (`max_values`: None, `max_size`: Some(151717), added: 154192, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::PendingFinalizations` (r:1 w:1)
	/// Proof: `Interoperability::PendingFinalizations` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn dispute_bridge_transaction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `595`
		//  Estimated: `155182`
		// Minimum execution time: 62_867_000 picoseconds.
		Weight::from_parts(65_996_000, 155182)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Interoperability::LiquidityPools` (r:1 w:1)
	/// Proof: `Interoperability::LiquidityPools` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	fn withdraw_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3576`
		// Minimum execution time: 41_555_000 picoseconds.
		Weight::from_parts(43_876_000, 3576)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Interoperability::BridgeTransactions` (r:1 w:0)
	/// Proof: `Interoperability::BridgeTransactions` (`max_values`: None, `max_size`: Some(151717), added: 154192, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BurnConfirmations` (r:1 w:1)
	/// Proof: `Interoperability::BurnConfirmations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Interoperability::BurnConfirmationCount` (r:1 w:1)
	/// Proof: `Interoperability::BurnConfirmationCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn confirm_burn_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `155182`
		// Minimum execution time: 29_505_000 picoseconds.
		Weight::from_parts(31_511_000, 155182)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}
