
//! Autogenerated weights for `pallet_storage_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_storage_proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/storage-proof/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_storage_proof` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `StorageProof::StorageProofs` (r:1 w:1)
	/// Proof: `StorageProof::StorageProofs` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 64]`.
	fn submit_storage_proof(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3550`
		// Minimum execution time: 44_164_000 picoseconds.
		Weight::from_parts(45_594_797, 3550)
			// Standard Error: 213
			.saturating_add(Weight::from_parts(622_682, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProof::StorageProofs` (r:1 w:1)
	/// Proof: `StorageProof::StorageProofs` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn revoke_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `3550`
		// Minimum execution time: 42_099_000 picoseconds.
		Weight::from_parts(44_133_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
