
//! Autogenerated weights for `pallet_belize_belizex`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_belizex
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/belizex/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_belizex` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `BelizeX::TradingPairs` (r:1 w:1)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn create_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `242`
		//  Estimated: `3538`
		// Minimum execution time: 22_751_000 picoseconds.
		Weight::from_parts(24_667_000, 3538)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:1 w:0)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TradingPairs` (r:1 w:1)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::LPBalances` (r:1 w:1)
	/// Proof: `BelizeX::LPBalances` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::LiquidityProviders` (r:1 w:1)
	/// Proof: `BelizeX::LiquidityProviders` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TourismTraders` (r:1 w:0)
	/// Proof: `BelizeX::TourismTraders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `3593`
		// Minimum execution time: 107_804_000 picoseconds.
		Weight::from_parts(112_520_000, 3593)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:1 w:0)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TradingPairs` (r:1 w:1)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::MerchantCategories` (r:1 w:0)
	/// Proof: `Oracle::MerchantCategories` (`max_values`: None, `max_size`: Some(358), added: 2833, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TourismTraders` (r:1 w:0)
	/// Proof: `BelizeX::TourismTraders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::LPBalances` (r:1 w:0)
	/// Proof: `BelizeX::LPBalances` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_trade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `490`
		//  Estimated: `6196`
		// Minimum execution time: 229_332_000 picoseconds.
		Weight::from_parts(241_412_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `BelizeX::TourismTraders` (r:0 w:1)
	/// Proof: `BelizeX::TourismTraders` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn register_tourism_trader() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_675_000 picoseconds.
		Weight::from_parts(12_839_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:1 w:0)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TradingPairs` (r:1 w:0)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::AccountOrderCount` (r:1 w:1)
	/// Proof: `BelizeX::AccountOrderCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::NextOrderId` (r:1 w:1)
	/// Proof: `BelizeX::NextOrderId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::OrderBook` (r:0 w:1)
	/// Proof: `BelizeX::OrderBook` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn place_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `3538`
		// Minimum execution time: 34_679_000 picoseconds.
		Weight::from_parts(37_342_000, 3538)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:0 w:1)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_911_000 picoseconds.
		Weight::from_parts(9_876_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:0 w:1)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn resume() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_954_000 picoseconds.
		Weight::from_parts(9_872_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BelizeX::TradingPairs` (r:1 w:1)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn set_pair_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `3538`
		// Minimum execution time: 22_891_000 picoseconds.
		Weight::from_parts(24_731_000, 3538)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:1 w:0)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::TradingPairs` (r:1 w:1)
	/// Proof: `BelizeX::TradingPairs` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::LPBalances` (r:1 w:1)
	/// Proof: `BelizeX::LPBalances` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::LiquidityProviders` (r:1 w:1)
	/// Proof: `BelizeX::LiquidityProviders` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `532`
		//  Estimated: `3593`
		// Minimum execution time: 105_721_000 picoseconds.
		Weight::from_parts(110_687_000, 3593)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `BelizeX::GlobalPaused` (r:1 w:0)
	/// Proof: `BelizeX::GlobalPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::OrderBook` (r:1 w:1)
	/// Proof: `BelizeX::OrderBook` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `BelizeX::AccountOrderCount` (r:1 w:1)
	/// Proof: `BelizeX::AccountOrderCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn cancel_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `368`
		//  Estimated: `3577`
		// Minimum execution time: 32_452_000 picoseconds.
		Weight::from_parts(34_569_000, 3577)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}
