
//! Autogenerated weights for `pallet_belize_landledger`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_landledger
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/landledger/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_landledger` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `LandLedger::PropertyByTitle` (r:1 w:1)
	/// Proof: `LandLedger::PropertyByTitle` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::NextPropertyId` (r:1 w:1)
	/// Proof: `LandLedger::NextPropertyId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::ZoningMap` (r:1 w:0)
	/// Proof: `LandLedger::ZoningMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::PropertyOwners` (r:1 w:1)
	/// Proof: `LandLedger::PropertyOwners` (`max_values`: None, `max_size`: Some(4050), added: 6525, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::PropertyAnchorChain` (r:0 w:1)
	/// Proof: `LandLedger::PropertyAnchorChain` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::Properties` (r:0 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::LandAnchors` (r:0 w:1)
	/// Proof: `LandLedger::LandAnchors` (`max_values`: None, `max_size`: Some(162), added: 2637, mode: `MaxEncodedLen`)
	fn register_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `7515`
		// Minimum execution time: 65_979_000 picoseconds.
		Weight::from_parts(69_245_000, 7515)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `LandLedger::Properties` (r:1 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::PropertyOwners` (r:2 w:2)
	/// Proof: `LandLedger::PropertyOwners` (`max_values`: None, `max_size`: Some(4050), added: 6525, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::NextTransferId` (r:1 w:1)
	/// Proof: `LandLedger::NextTransferId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::PropertyAnchorChain` (r:1 w:1)
	/// Proof: `LandLedger::PropertyAnchorChain` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::LandAnchors` (r:1 w:1)
	/// Proof: `LandLedger::LandAnchors` (`max_values`: None, `max_size`: Some(162), added: 2637, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::TransferRecords` (r:0 w:1)
	/// Proof: `LandLedger::TransferRecords` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn transfer_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `685`
		//  Estimated: `14040`
		// Minimum execution time: 137_175_000 picoseconds.
		Weight::from_parts(141_907_000, 14040)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `LandLedger::Properties` (r:1 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	fn verify_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `339`
		//  Estimated: `6995`
		// Minimum execution time: 23_186_000 picoseconds.
		Weight::from_parts(25_032_000, 6995)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LandLedger::GovernmentSurveyors` (r:1 w:0)
	/// Proof: `LandLedger::GovernmentSurveyors` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::Properties` (r:1 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	/// Storage: `LandLedger::ZoningMap` (r:1 w:0)
	/// Proof: `LandLedger::ZoningMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn survey_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `6995`
		// Minimum execution time: 32_885_000 picoseconds.
		Weight::from_parts(34_716_000, 6995)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LandLedger::GovernmentSurveyors` (r:0 w:1)
	/// Proof: `LandLedger::GovernmentSurveyors` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn register_surveyor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_599_000 picoseconds.
		Weight::from_parts(12_655_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LandLedger::GovernmentSurveyors` (r:1 w:1)
	/// Proof: `LandLedger::GovernmentSurveyors` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn remove_surveyor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3514`
		// Minimum execution time: 21_420_000 picoseconds.
		Weight::from_parts(22_940_000, 3514)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LandLedger::Properties` (r:1 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	fn add_encumbrance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3283`
		//  Estimated: `6995`
		// Minimum execution time: 29_732_000 picoseconds.
		Weight::from_parts(31_648_000, 6995)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LandLedger::Properties` (r:1 w:1)
	/// Proof: `LandLedger::Properties` (`max_values`: None, `max_size`: Some(3530), added: 6005, mode: `MaxEncodedLen`)
	fn remove_encumbrance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3592`
		//  Estimated: `6995`
		// Minimum execution time: 28_676_000 picoseconds.
		Weight::from_parts(30_681_000, 6995)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
