
//! Autogenerated weights for `pallet_belize_payroll`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_payroll
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/payroll/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_payroll` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeCountPerEmployer` (r:1 w:1)
	/// Proof: `Payroll::EmployeeCountPerEmployer` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::GlobalStats` (r:1 w:1)
	/// Proof: `Payroll::GlobalStats` (`max_values`: Some(1), `max_size`: Some(44), added: 539, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::DeptEmployeeCount` (r:1 w:1)
	/// Proof: `Payroll::DeptEmployeeCount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployerCount` (r:1 w:1)
	/// Proof: `Payroll::EmployerCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn add_employee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `185`
		//  Estimated: `3719`
		// Minimum execution time: 46_056_000 picoseconds.
		Weight::from_parts(48_880_000, 3719)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::GlobalStats` (r:1 w:1)
	/// Proof: `Payroll::GlobalStats` (`max_values`: Some(1), `max_size`: Some(44), added: 539, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeCountPerEmployer` (r:1 w:1)
	/// Proof: `Payroll::EmployeeCountPerEmployer` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::DeptEmployeeCount` (r:1 w:1)
	/// Proof: `Payroll::DeptEmployeeCount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployerCount` (r:1 w:1)
	/// Proof: `Payroll::EmployerCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeDeductions` (r:0 w:1)
	/// Proof: `Payroll::EmployeeDeductions` (`max_values`: None, `max_size`: Some(437), added: 2912, mode: `MaxEncodedLen`)
	fn remove_employee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `3719`
		// Minimum execution time: 58_137_000 picoseconds.
		Weight::from_parts(61_340_000, 3719)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	fn update_salary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `3719`
		// Minimum execution time: 33_234_000 picoseconds.
		Weight::from_parts(35_266_000, 3719)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeDeductions` (r:1 w:0)
	/// Proof: `Payroll::EmployeeDeductions` (`max_values`: None, `max_size`: Some(437), added: 2912, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::NextRecordId` (r:1 w:1)
	/// Proof: `Payroll::NextRecordId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::GlobalStats` (r:1 w:1)
	/// Proof: `Payroll::GlobalStats` (`max_values`: Some(1), `max_size`: Some(44), added: 539, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::PayrollRecords` (r:0 w:1)
	/// Proof: `Payroll::PayrollRecords` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
	fn execute_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `776`
		//  Estimated: `6196`
		// Minimum execution time: 124_527_000 picoseconds.
		Weight::from_parts(129_105_000, 6196)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:51 w:50)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:51 w:51)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeDeductions` (r:50 w:0)
	/// Proof: `Payroll::EmployeeDeductions` (`max_values`: None, `max_size`: Some(437), added: 2912, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::NextRecordId` (r:1 w:1)
	/// Proof: `Payroll::NextRecordId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::GlobalStats` (r:1 w:1)
	/// Proof: `Payroll::GlobalStats` (`max_values`: Some(1), `max_size`: Some(44), added: 539, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::PayrollRecords` (r:0 w:50)
	/// Proof: `Payroll::PayrollRecords` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 50]`.
	fn batch_payment(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300 + n * (343 ±0)`
		//  Estimated: `3719 + n * (2912 ±0)`
		// Minimum execution time: 146_904_000 picoseconds.
		Weight::from_parts(64_865_874, 3719)
			// Standard Error: 35_724
			.saturating_add(Weight::from_parts(86_786_982, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2912).saturating_mul(n.into()))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::NextScheduleId` (r:1 w:1)
	/// Proof: `Payroll::NextScheduleId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeCountPerEmployer` (r:1 w:0)
	/// Proof: `Payroll::EmployeeCountPerEmployer` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::PayrollSchedules` (r:0 w:1)
	/// Proof: `Payroll::PayrollSchedules` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn create_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3517`
		// Minimum execution time: 29_451_000 picoseconds.
		Weight::from_parts(31_232_000, 3517)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::PayrollSchedules` (r:1 w:1)
	/// Proof: `Payroll::PayrollSchedules` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn update_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3559`
		// Minimum execution time: 31_528_000 picoseconds.
		Weight::from_parts(33_416_000, 3559)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Payroll::EmployerProfiles` (r:1 w:1)
	/// Proof: `Payroll::EmployerProfiles` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::VerifiedEmployers` (r:0 w:1)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn verify_employer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3523`
		// Minimum execution time: 20_764_000 picoseconds.
		Weight::from_parts(22_341_000, 3523)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	fn toggle_employee_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `3719`
		// Minimum execution time: 31_977_000 picoseconds.
		Weight::from_parts(34_074_000, 3719)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployerProfiles` (r:1 w:1)
	/// Proof: `Payroll::EmployerProfiles` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Departments` (r:0 w:1)
	/// Proof: `Payroll::Departments` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn create_department() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3523`
		// Minimum execution time: 32_546_000 picoseconds.
		Weight::from_parts(34_321_000, 3523)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:0)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::EmployeeDeductions` (r:1 w:1)
	/// Proof: `Payroll::EmployeeDeductions` (`max_values`: None, `max_size`: Some(437), added: 2912, mode: `MaxEncodedLen`)
	fn set_deduction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `795`
		//  Estimated: `3902`
		// Minimum execution time: 38_551_000 picoseconds.
		Weight::from_parts(40_816_000, 3902)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Payroll::VerifiedEmployers` (r:1 w:0)
	/// Proof: `Payroll::VerifiedEmployers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::Employees` (r:1 w:1)
	/// Proof: `Payroll::Employees` (`max_values`: None, `max_size`: Some(254), added: 2729, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::NextRecordId` (r:1 w:1)
	/// Proof: `Payroll::NextRecordId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::GlobalStats` (r:1 w:1)
	/// Proof: `Payroll::GlobalStats` (`max_values`: Some(1), `max_size`: Some(44), added: 539, mode: `MaxEncodedLen`)
	/// Storage: `Payroll::PayrollRecords` (r:0 w:1)
	/// Proof: `Payroll::PayrollRecords` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
	fn issue_bonus() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `776`
		//  Estimated: `6196`
		// Minimum execution time: 121_388_000 picoseconds.
		Weight::from_parts(126_903_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}
