
//! Autogenerated weights for `pallet_belize_quantum`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_quantum
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/quantum/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_quantum` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Quantum::QuantumJobs` (r:1 w:1)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::JobsByAccount` (r:1 w:1)
	/// Proof: `Quantum::JobsByAccount` (`max_values`: None, `max_size`: Some(6650), added: 9125, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::TotalQuantumJobs` (r:1 w:1)
	/// Proof: `Quantum::TotalQuantumJobs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::TotalDallaSpent` (r:1 w:1)
	/// Proof: `Quantum::TotalDallaSpent` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::AccountStats` (r:1 w:1)
	/// Proof: `Quantum::AccountStats` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn submit_quantum_job() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `10115`
		// Minimum execution time: 60_737_000 picoseconds.
		Weight::from_parts(63_519_000, 10115)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Quantum::QuantumJobs` (r:1 w:1)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	fn update_job_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `3781`
		// Minimum execution time: 21_315_000 picoseconds.
		Weight::from_parts(23_048_000, 3781)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Quantum::ValidatorReputation` (r:1 w:0)
	/// Proof: `Quantum::ValidatorReputation` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumJobs` (r:1 w:1)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumResults` (r:1 w:1)
	/// Proof: `Quantum::QuantumResults` (`max_values`: None, `max_size`: Some(476), added: 2951, mode: `MaxEncodedLen`)
	fn record_quantum_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `3941`
		// Minimum execution time: 35_767_000 picoseconds.
		Weight::from_parts(38_200_000, 3941)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Quantum::QuantumResults` (r:1 w:0)
	/// Proof: `Quantum::QuantumResults` (`max_values`: None, `max_size`: Some(476), added: 2951, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumJobs` (r:1 w:1)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn verify_quantum_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `6196`
		// Minimum execution time: 63_434_000 picoseconds.
		Weight::from_parts(66_320_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Quantum::QuantumJobs` (r:1 w:0)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumResults` (r:1 w:0)
	/// Proof: `Quantum::QuantumResults` (`max_values`: None, `max_size`: Some(476), added: 2951, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTCounter` (r:1 w:1)
	/// Proof: `Quantum::NFTCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::AccountStats` (r:1 w:1)
	/// Proof: `Quantum::AccountStats` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumAchievements` (r:0 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	fn mint_achievement_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `3941`
		// Minimum execution time: 67_963_000 picoseconds.
		Weight::from_parts(71_958_000, 3941)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Quantum::BridgeRequests` (r:1 w:0)
	/// Proof: `Quantum::BridgeRequests` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	fn transfer_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3900`
		// Minimum execution time: 24_152_000 picoseconds.
		Weight::from_parts(26_178_000, 3900)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:0)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTListings` (r:1 w:1)
	/// Proof: `Quantum::NFTListings` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTAuctions` (r:1 w:0)
	/// Proof: `Quantum::NFTAuctions` (`max_values`: None, `max_size`: Some(169), added: 2644, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::ListingCounter` (r:1 w:1)
	/// Proof: `Quantum::ListingCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn list_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3900`
		// Minimum execution time: 30_986_000 picoseconds.
		Weight::from_parts(33_109_000, 3900)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Quantum::NFTListings` (r:1 w:1)
	/// Proof: `Quantum::NFTListings` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	fn buy_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `647`
		//  Estimated: `8799`
		// Minimum execution time: 199_570_000 picoseconds.
		Weight::from_parts(205_516_000, 8799)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Quantum::NFTListings` (r:1 w:1)
	/// Proof: `Quantum::NFTListings` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn delist_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `239`
		//  Estimated: `3585`
		// Minimum execution time: 22_739_000 picoseconds.
		Weight::from_parts(24_746_000, 3585)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTListings` (r:1 w:0)
	/// Proof: `Quantum::NFTListings` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTAuctions` (r:1 w:0)
	/// Proof: `Quantum::NFTAuctions` (`max_values`: None, `max_size`: Some(169), added: 2644, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::BridgeRequests` (r:1 w:1)
	/// Proof: `Quantum::BridgeRequests` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::BridgeCounter` (r:1 w:1)
	/// Proof: `Quantum::BridgeCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn bridge_to_ethereum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3900`
		// Minimum execution time: 37_983_000 picoseconds.
		Weight::from_parts(40_412_000, 3900)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTListings` (r:1 w:0)
	/// Proof: `Quantum::NFTListings` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::NFTAuctions` (r:1 w:0)
	/// Proof: `Quantum::NFTAuctions` (`max_values`: None, `max_size`: Some(169), added: 2644, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::BridgeRequests` (r:1 w:1)
	/// Proof: `Quantum::BridgeRequests` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::BridgeCounter` (r:1 w:1)
	/// Proof: `Quantum::BridgeCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn bridge_to_parachain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3900`
		// Minimum execution time: 38_309_000 picoseconds.
		Weight::from_parts(40_615_000, 3900)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Quantum::BridgeRequests` (r:1 w:1)
	/// Proof: `Quantum::BridgeRequests` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumAchievements` (r:1 w:1)
	/// Proof: `Quantum::QuantumAchievements` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	fn cancel_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `3900`
		// Minimum execution time: 30_660_000 picoseconds.
		Weight::from_parts(33_049_000, 3900)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Quantum::QuantumJobs` (r:1 w:0)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumResults` (r:1 w:0)
	/// Proof: `Quantum::QuantumResults` (`max_values`: None, `max_size`: Some(476), added: 2951, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::VerificationRequests` (r:1 w:1)
	/// Proof: `Quantum::VerificationRequests` (`max_values`: None, `max_size`: Some(873), added: 3348, mode: `MaxEncodedLen`)
	fn request_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `304`
		//  Estimated: `4338`
		// Minimum execution time: 31_839_000 picoseconds.
		Weight::from_parts(34_140_000, 4338)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Quantum::ValidatorReputation` (r:1 w:0)
	/// Proof: `Quantum::ValidatorReputation` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::QuantumJobs` (r:1 w:0)
	/// Proof: `Quantum::QuantumJobs` (`max_values`: None, `max_size`: Some(316), added: 2791, mode: `MaxEncodedLen`)
	/// Storage: `Quantum::VerificationRequests` (r:1 w:1)
	/// Proof: `Quantum::VerificationRequests` (`max_values`: None, `max_size`: Some(873), added: 3348, mode: `MaxEncodedLen`)
	fn submit_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `4338`
		// Minimum execution time: 36_750_000 picoseconds.
		Weight::from_parts(39_028_000, 4338)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
