
//! Autogenerated weights for `pallet_belize_economy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_economy
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/economy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_economy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Economy::LastMintRateLimitBlock` (r:1 w:1)
	/// Proof: `Economy::LastMintRateLimitBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Economy::MintingHalted` (r:1 w:0)
	/// Proof: `Economy::MintingHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Economy::AuthorizedMinters` (r:1 w:0)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:1)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::CentralBankReserves` (r:1 w:0)
	/// Proof: `Economy::CentralBankReserves` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::BBZDBalances` (r:1 w:1)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::MintCallsThisBlock` (r:0 w:1)
	/// Proof: `Economy::MintCallsThisBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn issue_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `297`
		//  Estimated: `4514`
		// Minimum execution time: 44_680_000 picoseconds.
		Weight::from_parts(47_444_000, 4514)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Economy::BBZDBalances` (r:1 w:1)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:1)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::NextRedemptionId` (r:1 w:1)
	/// Proof: `Economy::NextRedemptionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Economy::PendingRedemptionIds` (r:1 w:1)
	/// Proof: `Economy::PendingRedemptionIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::RedemptionRequests` (r:0 w:1)
	/// Proof: `Economy::RedemptionRequests` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	fn redeem_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `81487`
		// Minimum execution time: 43_592_000 picoseconds.
		Weight::from_parts(46_032_000, 81487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Economy::AuthorizedMinters` (r:1 w:0)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::RedemptionRequests` (r:1 w:1)
	/// Proof: `Economy::RedemptionRequests` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `Economy::PendingRedemptionIds` (r:1 w:1)
	/// Proof: `Economy::PendingRedemptionIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn process_redemption() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `403`
		//  Estimated: `81487`
		// Minimum execution time: 35_078_000 picoseconds.
		Weight::from_parts(37_307_000, 81487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Economy::AuthorizedMinters` (r:0 w:1)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn set_minter_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_747_000 picoseconds.
		Weight::from_parts(12_695_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Economy::CentralBankReserves` (r:1 w:1)
	/// Proof: `Economy::CentralBankReserves` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:0)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1501`
		// Minimum execution time: 13_838_000 picoseconds.
		Weight::from_parts(15_169_000, 1501)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	fn pay_tourism_incentive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `6196`
		// Minimum execution time: 135_862_000 picoseconds.
		Weight::from_parts(139_773_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_dalla() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 37_364_000 picoseconds.
		Weight::from_parts(38_986_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn governance_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3593`
		// Minimum execution time: 40_428_000 picoseconds.
		Weight::from_parts(42_554_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::LastInflationBlock` (r:0 w:1)
	/// Proof: `Economy::LastInflationBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_inflation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `8799`
		// Minimum execution time: 82_902_000 picoseconds.
		Weight::from_parts(85_223_000, 8799)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Economy::BBZDBalances` (r:2 w:2)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	fn transfer_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `6068`
		// Minimum execution time: 35_134_000 picoseconds.
		Weight::from_parts(37_325_000, 6068)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
