
//! Autogenerated weights for `pallet_belize_economy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-10-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wicked`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/wicked/Projects/Belizechain/belizechain/target/release/belizechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_belize_economy
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/wicked/Projects/Belizechain/belizechain/templates/weights-template.hbs
// --output
// /home/wicked/Projects/Belizechain/belizechain/pallets/economy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weights for `pallet_belize_economy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Economy::LastMintRateLimitBlock` (r:1 w:1)
	/// Proof: `Economy::LastMintRateLimitBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Economy::MintingHalted` (r:1 w:0)
	/// Proof: `Economy::MintingHalted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Economy::AuthorizedMinters` (r:1 w:0)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:1)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::CentralBankReserves` (r:1 w:0)
	/// Proof: `Economy::CentralBankReserves` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::BBZDBalances` (r:1 w:1)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::MintCallsThisBlock` (r:0 w:1)
	/// Proof: `Economy::MintCallsThisBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn issue_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `297`
		//  Estimated: `4514`
		// Minimum execution time: 45_848_000 picoseconds.
		Weight::from_parts(49_021_000, 4514)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Economy::BBZDBalances` (r:1 w:1)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:1)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::NextRedemptionId` (r:1 w:1)
	/// Proof: `Economy::NextRedemptionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Economy::PendingRedemptionIds` (r:1 w:1)
	/// Proof: `Economy::PendingRedemptionIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::RedemptionRequests` (r:0 w:1)
	/// Proof: `Economy::RedemptionRequests` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	fn redeem_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `81487`
		// Minimum execution time: 44_932_000 picoseconds.
		Weight::from_parts(48_055_000, 81487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Economy::AuthorizedMinters` (r:1 w:0)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::RedemptionRequests` (r:1 w:1)
	/// Proof: `Economy::RedemptionRequests` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `Economy::PendingRedemptionIds` (r:1 w:1)
	/// Proof: `Economy::PendingRedemptionIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn process_redemption() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `403`
		//  Estimated: `81487`
		// Minimum execution time: 35_929_000 picoseconds.
		Weight::from_parts(38_454_000, 81487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Economy::AuthorizedMinters` (r:0 w:1)
	/// Proof: `Economy::AuthorizedMinters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn set_minter_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_756_000 picoseconds.
		Weight::from_parts(12_949_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Economy::CentralBankReserves` (r:1 w:1)
	/// Proof: `Economy::CentralBankReserves` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalBbzdSupply` (r:1 w:0)
	/// Proof: `Economy::TotalBbzdSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1501`
		// Minimum execution time: 13_911_000 picoseconds.
		Weight::from_parts(15_321_000, 1501)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	/// Storage: `Economy::NextPaymentId` (r:1 w:1)
	/// Proof: `Economy::NextPaymentId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TourismPayments` (r:0 w:1)
	/// Proof: `Economy::TourismPayments` (`max_values`: None, `max_size`: Some(125), added: 2600, mode: `MaxEncodedLen`)
	fn pay_tourism_incentive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `289`
		//  Estimated: `6196`
		// Minimum execution time: 144_693_000 picoseconds.
		Weight::from_parts(150_063_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_dalla() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 37_559_000 picoseconds.
		Weight::from_parts(39_672_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn governance_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3593`
		// Minimum execution time: 41_279_000 picoseconds.
		Weight::from_parts(43_493_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Economy::TotalSupply` (r:0 w:1)
	/// Proof: `Economy::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Economy::LastInflationBlock` (r:0 w:1)
	/// Proof: `Economy::LastInflationBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_inflation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `8799`
		// Minimum execution time: 82_312_000 picoseconds.
		Weight::from_parts(86_562_000, 8799)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Economy::BBZDBalances` (r:2 w:2)
	/// Proof: `Economy::BBZDBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Compliance::TransactionWindow` (r:1 w:1)
	/// Proof: `Compliance::TransactionWindow` (`max_values`: None, `max_size`: Some(1049), added: 3524, mode: `MaxEncodedLen`)
	fn transfer_bbzd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `6068`
		// Minimum execution time: 36_322_000 picoseconds.
		Weight::from_parts(38_904_000, 6068)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
